### ISSUE TITLE
mysql error

### ISSUE THREAD

**Issue by PhanaticD** [GeorgH93/MarriageMaster#103]
I installed the plugin on a few spigot servers, then later installed it on bungee, and noticed this in the bungee startup log:

```
[04:38:51 INFO] [MarriageMaster]: Config file successfully loaded.
[04:38:51 INFO] [MarriageMaster]: Language file version newer than expected! Expected: 92 Is: 93
[04:38:51 INFO] [MarriageMaster]: Language file successfully loaded. Language: English  Author: GeorgH93
[04:38:51 INFO] [at.pcgamingfreaks.MarriageMasterStandalone.libs.com.zaxxer.hikari.HikariDataSource]: MarriageMaster-Connection-Pool - Starting...
[04:38:51 INFO] [at.pcgamingfreaks.MarriageMasterStandalone.libs.com.zaxxer.hikari.HikariDataSource]: MarriageMaster-Connection-Pool - Start completed.
[04:38:51 INFO] [MarriageMaster]: MySQL Server version: 10.4.10-MariaDB-1:10.4.10+maria~bionic
[04:38:51 ERROR]: java.sql.SQLException: Cannot drop index 'PRIMARY': needed in a foreign key constraint
[04:38:51 ERROR]:       at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965)
[04:38:51 ERROR]:       at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3978)
[04:38:51 ERROR]:       at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3914)
[04:38:51 ERROR]:       at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2530)
[04:38:51 ERROR]:       at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2683)
[04:38:51 ERROR]:       at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2491)
[04:38:51 ERROR]:       at com.mysql.jdbc.StatementImpl.executeUpdateInternal(StatementImpl.java:1552)
[04:38:51 ERROR]:       at com.mysql.jdbc.StatementImpl.executeLargeUpdate(StatementImpl.java:2607)
[04:38:51 ERROR]:       at com.mysql.jdbc.StatementImpl.executeUpdate(StatementImpl.java:1480)
[04:38:51 ERROR]:       at at.pcgamingfreaks.MarriageMasterStandalone.libs.com.zaxxer.hikari.pool.ProxyStatement.executeUpdate(ProxyStatement.java:120)
[04:38:51 ERROR]:       at at.pcgamingfreaks.MarriageMasterStandalone.libs.com.zaxxer.hikari.pool.HikariProxyStatement.executeUpdate(HikariProxyStatement.java)
[04:38:51 ERROR]:       at at.pcgamingfreaks.MarriageMasterStandalone.libs.at.pcgamingfreaks.Database.MySQLTableValidator.modifyPrimaryKey(MySQLTableValidator.java:132)
[04:38:51 ERROR]:       at at.pcgamingfreaks.MarriageMasterStandalone.libs.at.pcgamingfreaks.Database.SQLTableValidator.processConstraint(SQLTableValidator.java:215)
[04:38:51 ERROR]:       at at.pcgamingfreaks.MarriageMasterStandalone.libs.at.pcgamingfreaks.Database.SQLTableValidator.validate(SQLTableValidator.java:137)
[04:38:51 ERROR]:       at at.pcgamingfreaks.MarriageMasterStandalone.libs.at.pcgamingfreaks.Database.SQLTableValidator.validate(SQLTableValidator.java:70)
[04:38:51 ERROR]:       at at.pcgamingfreaks.MarriageMasterStandalone.libs.at.pcgamingfreaks.Database.DBTools.updateDB(DBTools.java:59)
[04:38:51 ERROR]:       at at.pcgamingfreaks.MarriageMasterStandalone.libs.at.pcgamingfreaks.Database.DBTools.updateDB(DBTools.java:89)
[04:38:51 ERROR]:       at at.pcgamingfreaks.MarriageMasterStandalone.Database.Backend.MySQL.checkDatabase(MySQL.java:126)
[04:38:51 ERROR]:       at at.pcgamingfreaks.MarriageMasterStandalone.Database.Backend.SQL.startup(SQL.java:85)
[04:38:51 ERROR]:       at at.pcgamingfreaks.MarriageMasterStandalone.Database.BaseDatabase.getDatabaseBackend(BaseDatabase.java:107)
[04:38:51 ERROR]:       at at.pcgamingfreaks.MarriageMasterStandalone.Database.BaseDatabase.<init>(BaseDatabase.java:67)
[04:38:51 ERROR]:       at at.pcgamingfreaks.MarriageMasterStandalone.Bungee.Database.Database.<init>(Database.java:38)
[04:38:51 ERROR]:       at at.pcgamingfreaks.MarriageMasterStandalone.Bungee.MarriageMaster.load(MarriageMaster.java:109)
[04:38:51 ERROR]:       at at.pcgamingfreaks.MarriageMasterStandalone.Bungee.MarriageMaster.onEnable(MarriageMaster.java:79)
[04:38:51 ERROR]:       at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:283)
[04:38:51 ERROR]:       at net.md_5.bungee.BungeeCord.start(BungeeCord.java:289)
[04:38:51 ERROR]:       at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:62)
[04:38:51 ERROR]:       at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
[04:38:51 INFO] [MarriageMaster]: Loading marriages ...
[04:38:51 INFO] [MarriageMaster]: Marriages loaded
[04:38:51 INFO] [MarriageMaster]: Loading priests ...
[04:38:51 INFO] [MarriageMaster]: Priests loaded
[04:38:51 INFO] [MarriageMaster]: Loading players ...
[04:38:51 INFO] [MarriageMaster]: Players loaded
[04:38:51 INFO] [MarriageMaster]: Writing marriages into cache ...
[04:38:51 INFO] [MarriageMaster]: Marriages loaded into cache
[04:38:51 INFO] [MarriageMaster]: Loading homes ...
[04:38:51 INFO] [MarriageMaster]: Homes loaded
[04:38:51 INFO] [MarriageMaster]: Marriage Master has been enabled!  :)
```

**Comment by GeorgH93** [comment]
Have you been using v1.x on your Spigot servers once? If so, please add
```
      Fields:
        PriestID: priest_id
```
to your BungeeCord config file under `Database.SQL.Tables` like this:
```
Database:
  UseUUIDs: true
  UseUUIDSeparators: false
  UUID_Type: auto
  SQL:
    Host: 'localhost'
    Database: 'minecraft'
    User: 'minecraft'
    Tables:
      User: marry_players
      Partner: marry_partners
      Home: marry_home
      Priests: marry_priests
      Fields:
        PriestID: priest_id
```


If you have not been using v1.x please check if your Spigot configs contain Fields definitions and make sure they are the same across all your servers (including BungeeCord).

**Comment by 1640946640** [comment]
Does it support the version 5.1.60 or 5.5.29 or 5.7.2.6 of mysql?
It seems like both of them can't work with this plugin.And other pulgins can working with
mysql normally.

**Comment by 1640946640** [comment]
> 您是否曾经在Spigot服务器上使用过v1.x？如果是这样，请添加
> 
> ```
>       Fields:
>         PriestID: priest_id
> ```
> 
> 到您的BungeeCord配置文件，`Database.SQL.Tables`如下所示：
> 
> ```
> Database:
>   UseUUIDs: true
>   UseUUIDSeparators: false
>   UUID_Type: auto
>   SQL:
>     Host: 'localhost'
>     Database: 'minecraft'
>     User: 'minecraft'
>     Tables:
>       User: marry_players
>       Partner: marry_partners
>       Home: marry_home
>       Priests: marry_priests
>       Fields:
>         PriestID: priest_id
> ```
> 
> 如果您尚未使用v1.x，请检查您的Spigot配置是否包含Fields定义，并确保它们在所有服务器（包括BungeeCord）上都相同。

Please help me to slove my question.

**Comment by GeorgH93** [comment]
They all should work. But I don't know why you would run such old MySQL server versions.

You can try to run `mysqlcheck --repair --all-databases -u root -p` in the terminal on your mysql server (and restart the mysql server afterwards). If it does not go away try to change the table names in the config like this:
```
Database:
  UseUUIDs: true
  UseUUIDSeparators: false
  UUID_Type: auto
  SQL:
    Host: 'localhost'
    Database: 'minecraft'
    User: 'minecraft'
    Tables:
      User: marryplayers
      Partner: marrypartners
      Home: marryhome
      Priests: marrypriests
```

**Comment by 1640946640** [comment]
> They all should work. But I don't know why you would run such old MySQL server versions.
> 
> You can try to run `mysqlcheck --repair --all-databases -u root -p` in the terminal on your mysql server (and restart the mysql server afterwards). If it does not go away try to change the table names in the config like this:
> 
> ```
> Database:
>   UseUUIDs: true
>   UseUUIDSeparators: false
>   UUID_Type: auto
>   SQL:
>     Host: 'localhost'
>     Database: 'minecraft'
>     User: 'minecraft'
>     Tables:
>       User: marryplayers
>       Partner: marrypartners
>       Home: marryhome
>       Priests: marrypriests
> ```
`[12:57:47] [MarriageMaster-Connection-Pool connection adder/WARN] []: Sat Jan 18 12:57:47 CST 2020 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.`
What should I do for this that I could solve it?

**Comment by GeorgH93** [comment]
Change `Properties: []` to `Properties: ["useSSL=false"]`
