### ISSUE TITLE
Error loading players

### ISSUE THREAD

**Issue by NoChanceSD** [GeorgH93/MarriageMaster#119]
### Information
**Environment information**
*Plugin + server version info*:
```
19.03 16:35:41 [Server] INFO ##### Start Marriage Master version info #####
19.03 16:35:41 [Server] INFO Marriage Master: 2.1.3-Release
19.03 16:35:41 [Server] INFO Server: git-Paper-d63075dff (MC: 1.15.2)
19.03 16:35:41 [Server] INFO #####  End Marriage Master version info  #####
```

*Online mode*: no
*BungeeCord*: yes

**Server/crash log**

```

[16:24:12] [Server thread/INFO]: [MarriageMaster] Updated 0 accounts to UUIDs.
[16:24:12] [Thread-26/INFO]: [MarriageMaster] Loading marriages ...
[16:24:12] [Thread-26/INFO]: [MarriageMaster] Marriages loaded
[16:24:12] [Thread-26/INFO]: [MarriageMaster] Loading priests ...
[16:24:12] [Thread-26/INFO]: [MarriageMaster] Priests loaded
[16:24:12] [Thread-26/INFO]: [MarriageMaster] Loading players ...
[16:24:12] [Thread-26/WARN]: java.lang.NullPointerException
[16:24:12] [Thread-26/WARN]: 	at at.pcgamingfreaks.MarriageMasterStandalone.Database.Backend.DatabaseBackend.getUUIDFromIdentifier(DatabaseBackend.java:70)
[16:24:12] [Thread-26/WARN]: 	at at.pcgamingfreaks.MarriageMasterStandalone.Database.Backend.SQL.loadAll(SQL.java:367)
[16:24:12] [Thread-26/WARN]: 	at at.pcgamingfreaks.MarriageMasterStandalone.Database.BaseDatabase$LoadRunnable.run(BaseDatabase.java:258)
[16:24:12] [Thread-26/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[16:24:12] [Thread-26/INFO]: [MarriageMaster] Players loaded
[16:24:12] [Thread-26/INFO]: [MarriageMaster] Writing marriages into cache ...
[16:24:12] [Thread-26/WARN]: [MarriageMaster] Player 1 for marriage 31 has not been loaded. Skipping
[16:24:12] [Thread-26/WARN]: [MarriageMaster] Player 1 for marriage 49 has not been loaded. Skipping
[16:24:12] [Thread-26/WARN]: [MarriageMaster] Player 1 for marriage 22 has not been loaded. Skipping
[16:24:12] [Thread-26/WARN]: [MarriageMaster] Player 1 for marriage 27 has not been loaded. Skipping
[16:24:12] [Thread-26/WARN]: [MarriageMaster] Player 2 for marriage 14 has not been loaded. Skipping

```

### Details
**Description**  

The plugin works fine but it seems to skip loading all the marriages because of the error while loading players, i get a bunch of warnings like the log above, where it skipps loading marriages.
When i use /marry list it doesn't show all the marriages, everything else seems to work.

**Steps to reproduce**  
I'm not sure when it started happening, i know previous versions used to work, i haven't touched the config either.

**Expected behavior**  
All marriages and players to load.

**Other information** (e.g. detailed explanation, related issues, suggestions how to fix, links for us to have context, screenshots, etc.)

**Comment by GeorgH93** [comment]
With Marriage Master v2.1 the plugin switched to always use UUIDs because maintaining two sets of logic (one for name as id and one for UUID as id) was to time consuming. You probably had UUIDs disabled previously. The plugin has attempted to convert the names to UUIDs, but some users have probably changed their name since they were married and thus can not be converted easily and are now causing the problem.
You will have to remove these players from the database.

*MySQL*
If you are using MySQL connect to your Database with your preferred tool and execute this query:
```SQL
DELETE FROM <database_name>.marry_players WHERE `uuid` IS NULL;
```
Replace `<database_name>` with the name of your database. If you have changed the table or field names in the config change them accordingly.

*SQLite*
If you are using SQLite, stop your server and open the database with an SQLite editor like [this](https://sqlitebrowser.org/). Then execute this query:
```SQL
DELETE FROM marry_players WHERE uuid IS NULL;
```
Save the changed and start the server again.

**Comment by NoChanceSD** [comment]
Thank you, seems to have worked.
