### ISSUE TITLE
1.12 update.

### ISSUE THREAD

**Issue by TheIntelloBox** [GeorgH93/MarriageMaster#13]
Hello ! :D 

Could you update Marriage Master V.2 to 1.12 ? :D 

Thanks ! :)

**Comment by GeorgH93** [comment]
The PCGF PluginLib should now be able to detect MC 1.12 correctly. So theoretically MMv2 should now work with MC 1.12 (I will have to do some more testing to be during the week to make sure).

**Comment by TheIntelloBox** [comment]
[17:46:26 ERROR]: Could not load 'plugins\MarriageMaster-2.0-SNAPSHOT (2).jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
        at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:160) ~[spigot-1.12-pre5.jar:git-Spigot-5b8313f-1004352]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:133) [spigot-1.12-pre5.jar:git-Spigot-5b8313f-1004352]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadPlugins(CraftServer.java:301) [spigot-1.12-pre5.jar:git-Spigot-5b8313f-1004352]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.reload(CraftServer.java:741) [spigot-1.12-pre5.jar:git-Spigot-5b8313f-1004352]
        at org.bukkit.Bukkit.reload(Bukkit.java:525) [spigot-1.12-pre5.jar:git-Spigot-5b8313f-1004352]
        at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:25) [spigot-1.12-pre5.jar:git-Spigot-5b8313f-1004352]
        at us.Myles.PWP.FakeSimpleCommandMap.dispatch(FakeSimpleCommandMap.java:95) [PerWorldPlugins.jar:?]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:643) [spigot-1.12-pre5.jar:git-Spigot-5b8313f-1004352]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchServerCommand(CraftServer.java:629) [spigot-1.12-pre5.jar:git-Spigot-5b8313f-1004352]
        at net.minecraft.server.v1_12_R1.DedicatedServer.aP(DedicatedServer.java:443) [spigot-1.12-pre5.jar:git-Spigot-5b8313f-1004352]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12-pre5.jar:git-Spigot-5b8313f-1004352]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot-1.12-pre5.jar:git-Spigot-5b8313f-1004352]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot-1.12-pre5.jar:git-Spigot-5b8313f-1004352]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]
Caused by: java.util.zip.ZipException: error in opening zip file
        at java.util.zip.ZipFile.open(Native Method) ~[?:1.8.0_131]
        at java.util.zip.ZipFile.<init>(Unknown Source) ~[?:1.8.0_131]
        at java.util.zip.ZipFile.<init>(Unknown Source) ~[?:1.8.0_131]
        at java.util.jar.JarFile.<init>(Unknown Source) ~[?:1.8.0_131]
        at java.util.jar.JarFile.<init>(Unknown Source) ~[?:1.8.0_131]
        at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:148) ~[spigot-1.12-pre5.jar:git-Spigot-5b8313f-1004352]
        ... 13 more
[17:46:26 ERROR]: Ambiguous plugin name `PCGF_PluginLib' for files `plugins\PluginLib-1.0-SNAPSHOT.jar' and `plugins\PluginLib-1.0-SNAPSHOT (1).jar' in `plugins'

**Comment by GeorgH93** [comment]
You have the same file twice in your plugins folder with different names.

**Comment by TheIntelloBox** [comment]
Okay sorry.
I have new errors : https://hastebin.com/oladevimaw.sql

**Comment by TheIntelloBox** [comment]
So ?

**Comment by GeorgH93** [comment]
Sorry it has taken that long.
Fix is available now: https://ci.pcgamingfreaks.at/job/PluginLib/106/artifact/target/PluginLib-1.0-SNAPSHOT.jar
