### ISSUE TITLE
PAPI 2.10.7

### ISSUE THREAD

**Issue by TNTUP** [GeorgH93/MarriageMaster#155]
### Information
**Environment information**
*Plugin + server version info*: 2.2.1-Release @ Paper 1.16.1 (Build 123) 

```

[18:21:44] [Client thread/INFO]: [CHAT] #############################
[18:21:49] [Client thread/INFO]: [CHAT] ##### Start Marriage Master version info #####
[18:21:49] [Client thread/INFO]: [CHAT] Marriage Master: 2.2.1-Release
[18:21:49] [Client thread/INFO]: [CHAT] Server: git-Paper-"6e7dc3f81" (MC: 1.16.1)
[18:21:49] [Client thread/INFO]: [CHAT] Java: 1.8.0_251
[18:21:49] [Client thread/INFO]: [CHAT] Minepacks: 2.3.11-Release
[18:21:49] [Client thread/INFO]: [CHAT] MVdWPlaceholderAPI: 3.0.1
[18:21:49] [Client thread/INFO]: [CHAT] PlaceholderAPI: 2.10.6
[18:21:49] [Client thread/INFO]: [CHAT] #####  End Marriage Master version info  #####


```

*Online mode*: (see BungeeCord)

*BungeeCord*: <!yes

**Server/crash log**

```

[0 18:15:14 ERROR]: Error occurred while disabling MarriageMaster v2.2.1-Release (Is it up to date?)
java.lang.NoSuchMethodError: me.clip.placeholderapi.PlaceholderAPI.unregisterExpansion(Lme/clip/placeholderapi/expansion/PlaceholderExpansion;)Z
        at at.pcgamingfreaks.MarriageMasterStandalone.Bukkit.Placeholder.Hooks.ClipsPlaceholderHook.close(ClipsPlaceholderHook.java:91) ~[?:?]
        at at.pcgamingfreaks.MarriageMasterStandalone.Bukkit.Placeholder.PlaceholderManager.close(PlaceholderManager.java:71) ~[?:?]
        at at.pcgamingfreaks.MarriageMasterStandalone.Bukkit.MarriageMaster.unload(MarriageMaster.java:249) ~[?:?]
        at at.pcgamingfreaks.MarriageMasterStandalone.Bukkit.MarriageMaster.onDisable(MarriageMaster.java:149) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[patched_1.12.2.jar:git-Paper-"8f7f4cf"]
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:350) ~[patched_1.12.2.jar:git-Paper-"8f7f4cf"]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:437) ~[patched_1.12.2.jar:git-Paper-"8f7f4cf"]
        at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:424) ~[patched_1.12.2.jar:git-Paper-"8f7f4cf"]
        at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:417) ~[patched_1.12.2.jar:git-Paper-"8f7f4cf"]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.disablePlugins(CraftServer.java:363) ~[patched_1.12.2.jar:git-Paper-"8f7f4cf"]
        at net.minecraft.server.v1_12_R1.MinecraftServer.stop(MinecraftServer.java:486) ~[patched_1.12.2.jar:git-Paper-"8f7f4cf"]
        at org.spigotmc.RestartCommand.shutdownServer(RestartCommand.java:90) ~[patched_1.12.2.jar:git-Paper-"8f7f4cf"]
        at org.spigotmc.RestartCommand.restart(RestartCommand.java:60) ~[patched_1.12.2.jar:git-Paper-"8f7f4cf"]
        at org.spigotmc.RestartCommand.restart(RestartCommand.java:40) ~[patched_1.12.2.jar:git-Paper-"8f7f4cf"]
        at org.spigotmc.RestartCommand$1.run(RestartCommand.java:31) ~[patched_1.12.2.jar:git-Paper-"8f7f4cf"]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:861) ~[patched_1.12.2.jar:git-Paper-"8f7f4cf"]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[patched_1.12.2.jar:git-Paper-"8f7f4cf"]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774) ~[patched_1.12.2.jar:git-Paper-"8f7f4cf"]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[patched_1.12.2.jar:git-Paper-"8f7f4cf"]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_251]

```

**Plugin config (optional)**

```

Not needed

```

### Details
**Description**  
No errors on startup, but it errors out while stopping server. I'm using ChatControl and the heart's placeholder still works however

**Steps to reproduce**  
Download latest PlacehodlerAPI 2.10.7
Download latest MarriageMaster 2.2.1

**Expected behavior**  
No errors in console from this pluggin

**Other information** (e.g. detailed explanation, related issues, suggestions how to fix, links for us to have context, screenshots, etc.)

PlaceholderAPI changed its API so deprecated methods are removed in this release

**Comment by GeorgH93** [comment]
They removed a method and introduced it's replacement in the same update. Love it.
I have implemented a solution that should make [this build](https://ci.pcgamingfreaks.at/job/MarriageMaster/215/artifact/artifacts/MarriageMaster-2.2.2-SNAPSHOT-Release.jar) work with the new and the old versions of PAPI.

**Comment by TNTUP** [comment]
> They removed a method and introduced it's replacement in the same update. Love it.
> I have implemented a solution that should make [this build](https://ci.pcgamingfreaks.at/job/MarriageMaster/215/artifact/artifacts/MarriageMaster-2.2.2-SNAPSHOT-Release.jar) work with the new and the old versions of PAPI.

Nice! Currently I'm using ChatControl so I can't really test all placeholders (I do only use the statusheart, the partner's name) but I'm confident MM's placeholderss will work :)

**Comment by GeorgH93** [comment]
They should. I have been using there new API since Marriage Master v2 has been released and all Placeholders get resolved in the same way.

They now removed the `PlaceholderAPI.unregisterExpansion` method and added an `unregister` method to the `PlaceholderExpansion` class (was expecting that such a method exists in there a long time ago since the method to register a placeholder is in that class too, but it was not), now we can register and unregister the our placeholder expansion in the same way, which is great, but that they also removed the old way in the same update as they added the new way is a bit annoying.

**Comment by TNTUP** [comment]
Yep xD
