### ISSUE TITLE
Several /marry commands don't work

### ISSUE THREAD

**Issue by hiddendragon98** [GeorgH93/MarriageMaster#160]
Several /marry commands fail to work. My server is currently running on Spigot 1.12.2.

The relevant console output is shown below:

[17:19:17 INFO]: hiddendragon98 issued server command: /marry
[17:19:17 INFO]: /marry
[17:19:17 WARN]: java.lang.NullPointerException
[17:19:17 WARN]: [MarriageMaster] Unhandled exception executing command 'marry ' in plugin MarriageMaster v2.2.7-Release
[17:19:17 WARN]: at at.pcgamingfreaks.MarriageMasterStandalone.Bukkit.Commands.CommandManagerImplementation.onCommand(CommandManagerImplementation.java:187)
[17:19:17 WARN]: at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[17:19:17 WARN]: at at.pcgamingfreaks.MarriageMasterStandalone.libs.at.pcgamingfreaks.Bukkit.Command.RegisterablePluginCommand.execute(RegisterablePluginCommand.java:142)
[17:19:17 WARN]: at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:648)
[17:19:17 WARN]: at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1401)
[17:19:17 WARN]: at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
[17:19:17 WARN]: at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1236)
[17:19:17 WARN]: at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13)
[17:19:17 WARN]: at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1)
[17:19:17 WARN]: at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[17:19:17 WARN]: at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[17:19:17 WARN]: at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
[17:19:17 WARN]: at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748)
[17:19:17 WARN]: at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
[17:19:17 WARN]: at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
[17:19:17 WARN]: at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
[17:19:17 WARN]: at java.lang.Thread.run(Thread.java:748)

**Comment by GeorgH93** [comment]
Please try if [this build ](https://ci.pcgamingfreaks.at/job/MarriageMaster/237/artifact/artifacts/MarriageMaster-2.2.8-SNAPSHOT-Release.jar)solves the problem for you.

**Comment by hiddendragon98** [comment]
Still gives an error:

[20:28:06 INFO]: hiddendragon98 issued server command: /marry
[20:28:06 INFO]: hiddendragon98 issued server command: /marry
[20:28:06 WARN]: java.lang.NullPointerException
[20:28:06 WARN]: [MarriageMaster] Unhandled exception executing command 'marry ' in plugin MarriageMaster v2.2.8-SNAPSHOT-Release
[20:28:06 WARN]: at at.pcgamingfreaks.MarriageMasterStandalone.Bukkit.Commands.CommandManagerImplementation.onCommand(CommandManagerImplementation.java:187)
[20:28:06 WARN]: at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[20:28:06 WARN]: at at.pcgamingfreaks.MarriageMasterStandalone.libs.at.pcgamingfreaks.Bukkit.Command.RegisterablePluginCommand.execute(RegisterablePluginCommand.java:142)
[20:28:06 WARN]: at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:648)
[20:28:06 WARN]: at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1236)
[20:28:06 WARN]: at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1401)
[20:28:06 WARN]: at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
[20:28:06 WARN]: at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13)
[20:28:06 WARN]: at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1)
[20:28:06 WARN]: at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[20:28:06 WARN]: at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[20:28:06 WARN]: at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748)
[20:28:06 WARN]: at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
[20:28:06 WARN]: at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
[20:28:06 WARN]: at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
[20:28:06 WARN]: at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
[20:28:06 WARN]: at java.lang.Thread.run(Thread.java:748)

**Comment by GeorgH93** [comment]
Is there any error when the plugin gets enabled?

**Comment by hiddendragon98** [comment]
[20:26:14] [Server thread/ERROR]: Error occurred while enabling MarriageMaster v2.2.8-SNAPSHOT-Release (Is it up to date?)
java.lang.NumberFormatException: For input string: ".5"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) ~[?:1.8.0_252]
	at java.lang.Integer.parseInt(Integer.java:569) ~[?:1.8.0_252]
	at java.lang.Integer.parseInt(Integer.java:615) ~[?:1.8.0_252]
	at at.pcgamingfreaks.MarriageMasterStandalone.libs.at.pcgamingfreaks.yaml.YamlGetter.getInt(YamlGetter.java:179) ~[?:?]
	at at.pcgamingfreaks.MarriageMasterStandalone.Bukkit.Database.Config.getKissWaitTime(Config.java:218) ~[?:?]
	at at.pcgamingfreaks.MarriageMasterStandalone.Bukkit.Commands.KissCommand.<init>(KissCommand.java:62) ~[?:?]
	at at.pcgamingfreaks.MarriageMasterStandalone.Bukkit.Commands.CommandManagerImplementation.init(CommandManagerImplementation.java:122) ~[?:?]
	at at.pcgamingfreaks.MarriageMasterStandalone.Bukkit.MarriageMaster.load(MarriageMaster.java:214) ~[?:?]
	at at.pcgamingfreaks.MarriageMasterStandalone.Bukkit.MarriageMaster.onEnable(MarriageMaster.java:128) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[Spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [Spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [Spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:381) [Spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:330) [Spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:422) [Spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:383) [Spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:338) [Spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [Spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [Spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]

**Comment by GeorgH93** [comment]
Should be fixed with [this build](https://ci.pcgamingfreaks.at/job/MarriageMaster/238/artifact/artifacts/MarriageMaster-2.2.8-SNAPSHOT-Release.jar).

**Comment by hiddendragon98** [comment]
Thank you, everything works normally now! ^_^
