### ISSUE TITLE
Marry seen error + no dev build update possible

### ISSUE THREAD

**Issue by TheoRetisch1** [GeorgH93/MarriageMaster#195]
### Information
**Environment information**
*Plugin + server version info*:
```
[21:14:37 INFO]: ##### Start Marriage Master version info #####
[21:14:37 INFO]: Marriage Master: 2.3.1-Release
[21:14:37 INFO]: PCGF PluginLib: 1.0.32-SNAPSHOT-T20210601180349
[21:14:37 INFO]: Server: git-Paper-732 (MC: 1.16.5)
[21:14:37 INFO]: Java: 1.8.0_231
[21:14:37 INFO]: PlaceholderAPI: 2.10.10-DEV-123
[21:14:37 INFO]: #####  End Marriage Master version info  #####
```

*Online mode*: yes

*BungeeCord*: no

**Server/crash log**
```
[21:16:34 INFO]: aerulion issued server command: /marry seen
[21:16:34 WARN]: [MarriageMaster] Unhandled exception executing command 'marry seen' in plugin MarriageMaster v2.3.1-Release
[21:16:34 WARN]: java.lang.ClassCastException: at.pcgamingfreaks.Bukkit.Message.Message cannot be cast to at.pcgamingfreaks.Bukkit.Message.IMessage
[21:16:34 WARN]:        at at.pcgamingfreaks.MarriageMaster.Bukkit.Database.MarriagePlayerData.sendMessage(MarriagePlayerData.java:44)
[21:16:34 WARN]:        at at.pcgamingfreaks.MarriageMaster.Bukkit.Commands.SeenCommand.execute(SeenCommand.java:60)
[21:16:34 WARN]:        at at.pcgamingfreaks.MarriageMaster.Bukkit.Commands.SeenCommand.execute(SeenCommand.java:35)
[21:16:34 WARN]:        at at.pcgamingfreaks.MarriageMaster.Bukkit.API.MarryCommand.doExecute(MarryCommand.java:149)
[21:16:34 WARN]:        at at.pcgamingfreaks.MarriageMaster.Bukkit.API.MarryCommand.doExecute(MarryCommand.java:35)
[21:16:34 WARN]:        at at.pcgamingfreaks.MarriageMaster.Bukkit.Commands.CommandManagerImplementation.onCommand(CommandManagerImplementation.java:177)
[21:16:34 WARN]:        at at.pcgamingfreaks.Bukkit.Command.RegisterablePluginCommand.execute(RegisterablePluginCommand.java:155)
[21:16:34 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[21:16:34 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:827)
[21:16:34 WARN]:        at net.minecraft.server.v1_16_R3.PlayerConnection.handleCommand(PlayerConnection.java:2185)
[21:16:34 WARN]:        at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:2000)
[21:16:34 WARN]:        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1953)
[21:16:34 WARN]:        at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:50)
[21:16:34 WARN]:        at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:8)
[21:16:34 WARN]:        at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:35)
[21:16:34 WARN]:        at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18)
[21:16:34 WARN]:        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
[21:16:34 WARN]:        at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[21:16:34 WARN]:        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
[21:16:34 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1265)
[21:16:34 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1258)
[21:16:34 WARN]:        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
[21:16:34 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1219)
[21:16:34 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1133)
[21:16:34 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:290)
[21:16:34 WARN]:        at java.lang.Thread.run(Thread.java:748)
```
https://i.imgur.com/GGUclnh.png
```
[19:53:52] [Server thread/INFO]: CreepyHDTV issued server command: /home nether
[19:55:00] [Server thread/INFO]: CreepyHDTV issued server command: /sethome nether
[19:55:04] [Server thread/INFO]: CreepyHDTV issued server command: /spawn
[19:55:04] [Server thread/INFO]: Die Fluggeschwindigkeit von CreepyHDTV wurde auf 1.29 gesetzt (Online).
[19:55:04] [Server thread/INFO]: CreepyHDTV time has been reset
[19:55:57] [Async Chat Thread - #56/INFO]: [corpchat] CreepyHDTV: gar keiner da? ist heute nicht Überraschungsevent?
[19:56:00] [Server thread/INFO]: CreepyHDTV issued server command: /back
[19:56:00] [Server thread/INFO]: Die Fluggeschwindigkeit von CreepyHDTV wurde auf 1.29 gesetzt (Online).
[19:56:00] [Server thread/INFO]: CreepyHDTV time has been reset
[19:56:56] [User Authenticator #25/INFO]: UUID of player LottaXL is c5400164-8f15-447e-9c39-207d4b27675d
[19:56:56] [Server thread/ERROR]: Could not pass event MarriedPlayerJoinEvent to MarriageMaster v2.3.1-Release
java.lang.ClassCastException: at.pcgamingfreaks.Bukkit.Message.Message cannot be cast to at.pcgamingfreaks.Bukkit.Message.IMessage
	at at.pcgamingfreaks.MarriageMaster.Bukkit.Database.MarriagePlayerData.send(MarriagePlayerData.java:44) ~[?:?]
	at at.pcgamingfreaks.MarriageMaster.Listener.JoinLeaveInfoBase.onJoin(JoinLeaveInfoBase.java:54) ~[?:?]
	at at.pcgamingfreaks.MarriageMaster.Bukkit.Listener.JoinLeaveInfo.onJoin(JoinLeaveInfo.java:44) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor424.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Paper-732]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Paper-732]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-732]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.16.5.jar:git-Paper-732]
	at at.pcgamingfreaks.MarriageMaster.Bukkit.Listener.JoinLeaveWorker.onJoin(JoinLeaveWorker.java:53) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor421.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Paper-732]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Paper-732]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-732]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.16.5.jar:git-Paper-732]
	at net.minecraft.server.v1_16_R3.PlayerList.postChunkLoadJoin(PlayerList.java:356) ~[patched_1.16.5.jar:git-Paper-732]
	at net.minecraft.server.v1_16_R3.PlayerList.lambda$a$1(PlayerList.java:303) ~[patched_1.16.5.jar:git-Paper-732]
	at net.minecraft.server.v1_16_R3.PlayerConnection.tick(PlayerConnection.java:316) ~[patched_1.16.5.jar:git-Paper-732]
	at net.minecraft.server.v1_16_R3.NetworkManager.a(NetworkManager.java:408) ~[patched_1.16.5.jar:git-Paper-732]
	at net.minecraft.server.v1_16_R3.ServerConnection.c(ServerConnection.java:168) ~[patched_1.16.5.jar:git-Paper-732]
	at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1514) ~[patched_1.16.5.jar:git-Paper-732]
	at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:436) ~[patched_1.16.5.jar:git-Paper-732]
	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1341) ~[patched_1.16.5.jar:git-Paper-732]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1129) ~[patched_1.16.5.jar:git-Paper-732]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:290) ~[patched_1.16.5.jar:git-Paper-732]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_231]
[19:56:56] [Server thread/INFO]: [+] LottaXL betritt Corp
[19:56:56] [Server thread/INFO]: LottaXL[/94.31.103.235:49589] logged in with entity id 456215 at ([weltn]-867.8875682148995, 68.0, 381.9748296985486)
[19:56:57] [Server thread/INFO]: LottaXL issued mycmd (gsbauIfOn) command /gsbauIfOn
[19:57:01] [Async Chat Thread - #57/INFO]: [corpchat] CreepyHDTV: hallo Lotta :D
[19:57:02] [Async Chat Thread - #57/INFO]: [corpchat] Doomcraft282: huhu
[19:57:08] [Async Chat Thread - #57/INFO]: [corpchat] LottaXL: hallo :)
[19:57:24] [Server thread/INFO]: CreepyHDTV issued server command: /home lager
[19:57:24] [Server thread/INFO]: Die Fluggeschwindigkeit von CreepyHDTV wurde auf 1.29 gesetzt (Online).
[19:57:24] [Server thread/INFO]: CreepyHDTV time has been reset
[19:57:40] [Server thread/INFO]: LottaXL issued server command: /warp 4gewinnt
[19:59:14] [Async Chat Thread - #58/INFO]: [corpchat] LottaXL: Gleich startet das wöchentliche Überraschungsevent =) Heute spielen wir 4-gewinnt !
[19:59:36] [Async Chat Thread - #58/INFO]: [corpchat] LottaXL:  Wir brauchen mindestens 3 Teilnehmer bei /warp 4gewinnt
```

**Plugin config (optional)**
https://gist.github.com/TheoRetisch1/31572f3098eade15e450f2ddec85c6c1

### Details
**Description** 
MarriageMaster throws an error from time to time and when entering /marry seen. If Marriage Master is updated to the dev-build MarriageMaster-2.4-RC4 - 281, Marriage Master will no longer load at all: 
https://gist.github.com/TheoRetisch1/106c4ff448a47e3013d703211470d4d2

**Steps to reproduce**  
I have updated Paper  from build 586 to build 732 using MarriageMaster version 2.3.1. After that I tried to update to MarriageMaster-2.4-RC4 build 281. 

**Expected behavior**  
Marriage Master works as intended and does not throw any errors.

**Comment by GeorgH93** [comment]
This is caused by the changes recently introduced into spigot by [this commit](https://hub.spigotmc.org/stash/projects/SPIGOT/repos/bukkit/commits/146a7e4bd764990c56bb326643e92eb69f24d27e).
I am already working on it.

For now you can use [this build](https://ci.pcgamingfreaks.at/job/MarriageMaster/283/artifact/artifacts/MarriageMaster-2.4-RC4.jar), it should resolve the issue.

**Comment by TheoRetisch1** [comment]
Thanks, unfortunatly I get the following error trying to update to the provided build, MarriageMaster won't load:
```
[06:47:47] [Server thread/INFO]: [MarriageMaster] Enabling MarriageMaster v2.4-RC4-T20210603202612
[06:47:47] [Server thread/INFO]: [MarriageMaster] [32mConfig file successfully loaded.[0m
[06:47:47] [Server thread/INFO]: [MarriageMaster] No compatible backpack plugin found.
[06:47:47] [Server thread/INFO]: [MarriageMaster] [32mLanguage file successfully loaded. Language: German  Author: GeorgH93[0m
[06:47:47] [Server thread/INFO]: [at.pcgf.libs.com.zaxxer.hikari.HikariDataSource] MarriageMaster-Connection-Pool - Starting...
[06:47:47] [Server thread/INFO]: [at.pcgf.libs.com.zaxxer.hikari.HikariDataSource] MarriageMaster-Connection-Pool - Start completed.
[06:47:47] [Thread-62/INFO]: [MarriageMaster] Loading marriages ...
[06:47:47] [Thread-62/INFO]: [MarriageMaster] Marriages loaded
[06:47:47] [Thread-62/INFO]: [MarriageMaster] Loading priests ...
[06:47:47] [Thread-62/INFO]: [MarriageMaster] Priests loaded
[06:47:47] [Thread-62/INFO]: [MarriageMaster] Loading players ...
[06:47:47] [Thread-62/INFO]: [MarriageMaster] Players loaded
[06:47:47] [Thread-62/INFO]: [MarriageMaster] Writing marriages into cache ...
[06:47:47] [Thread-62/INFO]: [MarriageMaster] Marriages loaded into cache
[06:47:47] [Thread-62/INFO]: [MarriageMaster] Loading homes ...
[06:47:47] [Thread-62/INFO]: [MarriageMaster] Homes loaded
[06:47:47] [Server thread/INFO]: [MarriageMaster] No translation for key: Ingame.ListPriests.NoPriestsOnline
[06:47:47] [Server thread/ERROR]: Error occurred while enabling MarriageMaster v2.4-RC4-T20210603202612 (Is it up to date?)
java.lang.IllegalArgumentException: Collection is empty
	at java.util.EnumSet.copyOf(EnumSet.java:174) ~[?:1.8.0_231]
	at at.pcgamingfreaks.MarriageMaster.Bukkit.Database.Config.getGiftAllowedGameModes(Config.java:252) ~[?:?]
	at at.pcgamingfreaks.MarriageMaster.Bukkit.Commands.GiftCommand.<init>(GiftCommand.java:80) ~[?:?]
	at at.pcgamingfreaks.MarriageMaster.Bukkit.Commands.CommandManagerImplementation.init(CommandManagerImplementation.java:114) ~[?:?]
	at at.pcgamingfreaks.MarriageMaster.Bukkit.MarriageMaster.load(MarriageMaster.java:212) ~[?:?]
	at at.pcgamingfreaks.MarriageMaster.Bukkit.MarriageMaster.onEnable(MarriageMaster.java:126) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.5.jar:git-Paper-762]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.16.5.jar:git-Paper-762]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.16.5.jar:git-Paper-762]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:518) ~[patched_1.16.5.jar:git-Paper-762]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:432) ~[patched_1.16.5.jar:git-Paper-762]
	at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:594) ~[patched_1.16.5.jar:git-Paper-762]
	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:298) ~[patched_1.16.5.jar:git-Paper-762]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1069) ~[patched_1.16.5.jar:git-Paper-762]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-762]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_231]
[06:47:47] [Server thread/INFO]: [MarriageMaster] Disabling MarriageMaster v2.4-RC4-T20210603202612
[06:47:47] [Server thread/ERROR]: Error occurred while disabling MarriageMaster v2.4-RC4-T20210603202612 (Is it up to date?)
java.lang.NullPointerException: null
	at at.pcgamingfreaks.MarriageMaster.Bukkit.MarriageMaster.unload(MarriageMaster.java:247) ~[?:?]
	at at.pcgamingfreaks.MarriageMaster.Bukkit.MarriageMaster.onDisable(MarriageMaster.java:147) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[patched_1.16.5.jar:git-Paper-762]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:405) ~[patched_1.16.5.jar:git-Paper-762]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:533) ~[patched_1.16.5.jar:git-Paper-762]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:374) ~[patched_1.16.5.jar:git-Paper-762]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.16.5.jar:git-Paper-762]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:518) ~[patched_1.16.5.jar:git-Paper-762]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:432) ~[patched_1.16.5.jar:git-Paper-762]
	at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:594) ~[patched_1.16.5.jar:git-Paper-762]
	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:298) ~[patched_1.16.5.jar:git-Paper-762]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1069) ~[patched_1.16.5.jar:git-Paper-762]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-762]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_231]
```

**Comment by GeorgH93** [comment]
Please try [this build](https://ci.pcgamingfreaks.at/job/MarriageMaster/284/artifact/artifacts/MarriageMaster-2.4-RC4.jar).

For now you can use [this build](https://ci.pcgamingfreaks.at/job/MarriageMaster/283/artifact/artifacts/MarriageMaster-2.4-RC4.jar), it should resolve the issue.

**Comment by TheoRetisch1** [comment]
The provided build worked, thank you very much 💯
