### ISSUE TITLE
BUG CONSOLE

### ISSUE THREAD

**Issue by srfabric** [GeorgH93/MarriageMaster#242]
I don´t know why this appears.

[14:11:29 WARN]: org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (table marry_players has no column named {FShareBackpack})
[14:11:29 WARN]:        at org.sqlite.core.DB.newSQLException(DB.java:1030)
[14:11:29 WARN]:        at org.sqlite.core.DB.newSQLException(DB.java:1042)
[14:11:29 WARN]:        at org.sqlite.core.DB.throwex(DB.java:1007)
[14:11:29 WARN]:        at org.sqlite.core.NativeDB.prepare_utf8(Native Method)
[14:11:29 WARN]:        at org.sqlite.core.NativeDB.prepare(NativeDB.java:137)
[14:11:29 WARN]:        at org.sqlite.core.DB.prepare(DB.java:257)
[14:11:29 WARN]:        at org.sqlite.core.CorePreparedStatement.<init>(CorePreparedStatement.java:45)
[14:11:29 WARN]:        at org.sqlite.jdbc3.JDBC3PreparedStatement.<init>(JDBC3PreparedStatement.java:30)
[14:11:29 WARN]:        at org.sqlite.jdbc4.JDBC4PreparedStatement.<init>(JDBC4PreparedStatement.java:25)
[14:11:29 WARN]:        at org.sqlite.jdbc4.JDBC4Connection.prepareStatement(JDBC4Connection.java:35)
[14:11:29 WARN]:        at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:241)
[14:11:29 WARN]:        at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:205)
[14:11:29 WARN]:        at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:214)
[14:11:29 WARN]:        at MarriageMaster.jar//at.pcgamingfreaks.MarriageMasterStandalone.libs.com.zaxxer.hikari.pool.ProxyConnection.prepareStatement(ProxyConnection.java:322)
[14:11:29 WARN]:        at MarriageMaster.jar//at.pcgamingfreaks.MarriageMasterStandalone.libs.com.zaxxer.hikari.pool.HikariProxyConnection.prepareStatement(HikariProxyConnection.java)
[14:11:29 WARN]:        at MarriageMaster.jar//at.pcgamingfreaks.MarriageMasterStandalone.Database.Backend.SQL.add(SQL.java:512)
[14:11:29 WARN]:        at MarriageMaster.jar//at.pcgamingfreaks.MarriageMasterStandalone.Database.Backend.SQL.doLoad(SQL.java:496)
[14:11:29 WARN]:        at MarriageMaster.jar//at.pcgamingfreaks.MarriageMasterStandalone.Database.Backend.SQL.lambda$load$3(SQL.java:487)
[14:11:29 WARN]:        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101)
[14:11:29 WARN]:        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[14:11:29 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[14:11:29 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[14:11:29 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[14:11:29 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by GeorgH93** [comment]
Please update to [this build](https://ci.pcgamingfreaks.at/job/MarriageMaster/365/artifact/artifacts/MarriageMaster-2.5.5-SNAPSHOT-Release.jar).

**Comment by srfabric** [comment]
![image](https://user-images.githubusercontent.com/95653654/147399541-ce0e74d7-dbb0-429c-b38f-9251e046e1fa.png)

**Comment by srfabric** [comment]
i should eliminate the database to it generate again? and if yes, there are any way to don´t lose the data?

**Comment by GeorgH93** [comment]
Not sure why the column is still missing. Have you created the database with the broken version?

You should be able to fix with [sqlitebrowser](https://sqlitebrowser.org/).
1. Open the `database.db` file with it.
2. Click on the `marry_players` row and then `Modify Table`
3. There should be 4 rows in the Fields list (`player_id`, `name`, `uuid`, `sharebackpack`). If there is any other row there, click it and then click `Remove`.
4. Now you can create the `sharebackpack` field. Click on `Add`, it will add an new row, set it to the following values: Name=`sharebackpack`, Type=`INTEGER`, NN=selected, Default=`0`
When you are done, it should look like this:
![image](https://user-images.githubusercontent.com/5041277/147415575-c8cc58bf-9e17-419f-b0f9-66cbf4ff39d3.png)
5. Click on `OK`
6. Exit and reload MarriageMaster.

Your data should be able to load again.
