### ISSUE TITLE
MarriageMaster doesn't load

### ISSUE THREAD

**Issue by TheoRetisch1** [GeorgH93/MarriageMaster#250]
**Environment information**
*Plugin + server version info*:
```
 MarriageMaster version 2.5.6-SNAPSHOT-T20220203173416
```

*Online mode*: yes

*BungeeCord*: no

**Server/crash log**
```
[10:35:21 INFO]: [MarriageMaster] Enabling MarriageMaster v2.5.6-SNAPSHOT-T20220203173416
[10:35:21 INFO]: [MarriageMaster] Config file successfully loaded.
[10:35:21 INFO]: [MarriageMaster] No compatible backpack plugin found.
[10:35:21 ERROR]: Error occurred while enabling MarriageMaster v2.5.6-SNAPSHOT-T20220203173416 (Is it up to date?)
java.lang.IncompatibleClassChangeError: Class at.pcgamingfreaks.MarriageMaster.Bukkit.Database.Config does not implement the requested int
erface at.pcgamingfreaks.Config.ILanguageConfiguration
        at at.pcgamingfreaks.Language.load(Language.java:282) ~[PCGF_PluginLib.jar:?]
        at at.pcgamingfreaks.MarriageMaster.Bukkit.MarriageMaster.load(MarriageMaster.java:167) ~[MarriageMaster.jar:?]
        at at.pcgamingfreaks.MarriageMaster.Bukkit.MarriageMaster.onEnable(MarriageMaster.java:128) ~[MarriageMaster.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugin(CraftServer.java:564) ~[paper-1.18.1.jar:git-Paper-187]
        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugins(CraftServer.java:478) ~[paper-1.18.1.jar:git-Paper-187]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:727) ~[paper-1.18.1.jar:git-Paper-187]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:503) ~[paper-1.18.1.jar:git-Paper-187]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:313) ~[paper-1.18.1.jar:git-Paper-187]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1202) ~[paper-1.18.1.jar:git-Paper-187]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.1.jar:git-Paper-187]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[10:35:21 INFO]: [MarriageMaster] Disabling MarriageMaster v2.5.6-SNAPSHOT-T20220203173416
[10:35:21 INFO]: [MarriageMaster]  Marriage Master has been disabled.  :(
```

**Plugin config (optional)**
```
https://gist.github.com/TheoRetisch1/774dab579f9e263b8231e847bce3046d
```

### Details
**Description**  
MarriageMaster suddenly stops loading after working fine for months. I can't figure out the problem. On startup, the error pasted above appears. I have tried Paper on the latest version and on version-169. Downloaded the latest MarriageMaster and PCGF_PluginLib dev build. Reduced the plugins from 82 to 11 to an absolute minimum, but MarriageMaster just won't load. What could be the problem?

**Steps to reproduce**  
Use Paper 1.18.1 and the latest MarriageMaster + PCGF_PluginLib builds and start the server. 

**Expected behavior**  
Marriage Master should load.

**Comment by TheoRetisch1** [comment]
I resetet my config and my database, it didn't helped. Now I downloaded `version 2.5.5.1` from Spigiot an the plugin finally loads with the old configuration and without any issues. The dev-builds doesn't work for me and cause the error.

**Comment by GeorgH93** [comment]
Thanks for telling me, looks like I have broken something that was expected by my recent changes to the PCGF PluginLib.
If you need something feature from the dev builds, it should work again with [this build](https://ci.pcgamingfreaks.at/job/MarriageMaster/400/artifact/artifacts/MarriageMaster-2.5.6-SNAPSHOT-Release.jar).

**Comment by TheoRetisch1** [comment]
Thanks!
