### ISSUE TITLE
Marry messages bug

### ISSUE THREAD

**Issue by thiagogebrimm** [GeorgH93/MarriageMaster#290]
In new versions all messages are having this problem, we can't use any command

```
[13:38:24 ERROR]: Could not pass event MarriedPlayerQuitEvent to MarriageMaster
java.lang.ClassCastException: class at.pcgamingfreaks.Bukkit.Message.Message cannot be cast to class at.pcgamingfreaks.Bukkit.Message.IMessage (at.pcgamingfreaks.Bukkit.Message.Message is in unnamed module of loader 'PCGF_PluginLib-1.0.38-SNAPSHOT.jar' @75478ae2; at.pcgamingfreaks.Bukkit.Message.IMessage is in unnamed module of loader java.net.URLClassLoader @c0b9d16)
        at at.pcgamingfreaks.MarriageMaster.Bukkit.Database.MarriagePlayerData.send(MarriagePlayerData.java:47) ~[MarriageMaster.jar:?]
        at at.pcgamingfreaks.MarriageMaster.Listener.JoinLeaveInfoBase.onLeave(JoinLeaveInfoBase.java:67) ~[MarriageMaster.jar:?]
        at at.pcgamingfreaks.MarriageMaster.Bukkit.Listener.JoinLeaveInfo.onLeave(JoinLeaveInfo.java:50) ~[MarriageMaster.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor845.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:git-Purpur-1923]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.19.3.jar:git-Purpur-1923]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[purpur-1.19.3.jar:git-Purpur-1923]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at at.pcgamingfreaks.MarriageMaster.Bukkit.Listener.JoinLeaveWorker.onLeave(JoinLeaveWorker.java:64) ~[MarriageMaster.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor840.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:git-Purpur-1923]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.19.3.jar:git-Purpur-1923]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[purpur-1.19.3.jar:git-Purpur-1923]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.players.PlayerList.remove(PlayerList.java:581) ~[purpur-1.19.3.jar:git-Purpur-1923]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.onDisconnect(ServerGamePacketListenerImpl.java:2210) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.disconnect(ServerGamePacketListenerImpl.java:557) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.disconnect(ServerGamePacketListenerImpl.java:498) ~[?:?]
        at org.bukkit.craftbukkit.v1_19_R2.entity.CraftPlayer.kickPlayer(CraftPlayer.java:607) ~[purpur-1.19.3.jar:git-Purpur-1923]
        at com.earth2me.essentials.commands.Commandkickall.run(Commandkickall.java:23) ~[EssentialsX-2.20.0-dev+43-25ad8ac.jar:?]
        at com.earth2me.essentials.commands.EssentialsCommand.run(EssentialsCommand.java:180) ~[EssentialsX-2.20.0-dev+43-25ad8ac.jar:?]
        at com.earth2me.essentials.Essentials.onCommandEssentials(Essentials.java:818) ~[EssentialsX-2.20.0-dev+43-25ad8ac.jar:?]
        at com.earth2me.essentials.Essentials.onCommand(Essentials.java:723) ~[EssentialsX-2.20.0-dev+43-25ad8ac.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:168) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.dispatchCommand(CraftServer.java:926) ~[purpur-1.19.3.jar:git-Purpur-1923]
        at dev.norska.uar.tasks.UARCountdown$1$3.run(UARCountdown.java:143) ~[UltimateAutoRestart+ Build 52c.jar:?]
        at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.19.3.jar:git-Purpur-1923]
        at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[purpur-1.19.3.jar:git-Purpur-1923]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1500) ~[purpur-1.19.3.jar:git-Purpur-1923]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:488) ~[purpur-1.19.3.jar:git-Purpur-1923]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1424) ~[purpur-1.19.3.jar:git-Purpur-1923]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1194) ~[purpur-1.19.3.jar:git-Purpur-1923]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[purpur-1.19.3.jar:git-Purpur-1923]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by GeorgH93** [comment]
Which version of paper are you using?

**Comment by GeorgH93** [comment]
The new paper plugin loading is a bit of a mess right now.
You can try if [this build](https://ci.pcgamingfreaks.at/job/MarriageMaster/461/artifact/artifacts/MarriageMaster-2.6.11-Release.jar) solves the problem for you.
If not, you can use [this version](https://github.com/GeorgH93/MarriageMaster/releases/download/v2.6.11/MarriageMaster-2.6.11-Standalone.jar), but this might not hook correctly with other plugins.

**Comment by thiagogebrimm** [comment]
Solved in dev version!
