### ISSUE TITLE
Failed to run bootstrapper for plugins/MarriageMaster.jar.

### ISSUE THREAD

**Issue by DarkKingArthas** [GeorgH93/MarriageMaster#300]
### Help request

**Problem**
The plugin does not load and gives an error.
[ERROR]: [BootstrapProviderStorage] Failed to run bootstrapper for plugins/MarriageMaster.jar. This plugin will not be loaded.

`Starting org.bukkit.craftbukkit.Main
System Info: Java 20 (OpenJDK 64-Bit Server VM 20.0.1+9) Host: Linux 6.3.6-arch1-1 (amd64)
Loading libraries, please wait...
[03:35:06 INFO]: [SparkProviderSource] Purpur: Using user-provided spark plugin instead of our own.
[03:35:10 ERROR]: [BootstrapProviderStorage] Failed to run bootstrapper for plugins/MarriageMaster.jar. This plugin will not be loaded.
java.lang.AbstractMethodError: Receiver class at.pcgamingfreaks.MarriageMaster.Paper.MarriageMasterBootstrap does not define or inherit an implementation of the resolved method 'abstract void bootstrap(io.papermc.paper.plugin.bootstrap.BootstrapContext)' of interface io.papermc.paper.plugin.bootstrap.PluginBootstrap.
	at io.papermc.paper.plugin.storage.BootstrapProviderStorage$1.load(BootstrapProviderStorage.java:34) ~[purpur-1.19.4.jar:git-Purpur-1984]
	at io.papermc.paper.plugin.storage.BootstrapProviderStorage$1.load(BootstrapProviderStorage.java:22) ~[purpur-1.19.4.jar:git-Purpur-1984]
	at io.papermc.paper.plugin.entrypoint.strategy.modern.ModernPluginLoadingStrategy.loadProviders(ModernPluginLoadingStrategy.java:117) ~[purpur-1.19.4.jar:git-Purpur-1984]
	at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:39) ~[purpur-1.19.4.jar:git-Purpur-1984]
	at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36) ~[purpur-1.19.4.jar:git-Purpur-1984]
	at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enterBootstrappers(LaunchEntryPointHandler.java:26) ~[purpur-1.19.4.jar:git-Purpur-1984]
	at net.minecraft.server.Bootstrap.lambda$bootStrap$0(Bootstrap.java:75) ~[?:?]
	at net.minecraft.core.registries.BuiltInRegistries.bootStrap(BuiltInRegistries.java:321) ~[purpur-1.19.4.jar:git-Purpur-1984]
	at net.minecraft.server.Bootstrap.bootStrap(Bootstrap.java:73) ~[?:?]
	at net.minecraft.server.Main.main(Main.java:127) ~[purpur-1.19.4.jar:git-Purpur-1984]
	at org.bukkit.craftbukkit.Main.main(Main.java:330) ~[purpur-1.19.4.jar:git-Purpur-1984]
	at io.papermc.paperclip.Paperclip.lambda$main$0(Paperclip.java:42) ~[app:?]
	at java.lang.Thread.run(Thread.java:1623) ~[?:?]
`

**What I have tried**

The plugin worked before, I thought it was related to the latest 2.7 update, but going back to the previous version didn't help.

Maybe it's related to Purpur, but it was working on Purpur, I updated that too, maybe it's related to the update. Not sure, in any case even if there was an update, it shouldn't be like that after all.

**Comment by GeorgH93** [comment]
Paper team pushed changes that break their new plugin API with build 549. Update is on it's way.

**Comment by GeorgH93** [comment]
Fix is available: https://github.com/GeorgH93/MarriageMaster/releases/tag/v2.7.0.1
