### ISSUE TITLE
Checking for updates does not work

### ISSUE THREAD

**Issue by aml2023529** [GeorgH93/MarriageMaster#304]
[17:53:45 INFO]: Ami_donkey issued server command: /matrix update
[17:53:46 ERROR]: [MarriageMaster] Failed to query spigot api for updates.
java.net.SocketException: Connection reset
        at sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:313) ~[?:?]
        at sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:340) ~[?:?]
        at sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:789) ~[?:?]
        at java.net.Socket$SocketInputStream.read(Socket.java:1025) ~[?:?]
        at sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:483) ~[?:?]
        at sun.security.ssl.SSLSocketInputRecord.readHeader(SSLSocketInputRecord.java:477) ~[?:?]
        at sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:160) ~[?:?]
        at sun.security.ssl.SSLTransport.decode(SSLTransport.java:111) ~[?:?]
        at sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1506) ~[?:?]
        at sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1421) ~[?:?]
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:455) ~[?:?]
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:426) ~[?:?]
        at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:587) ~[?:?]
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:187) ~[?:?]
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1657) ~[?:?]
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1581) ~[?:?]
        at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:529) ~[?:?]
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:308) ~[?:?]
        at at.pcgamingfreaks.MarriageMasterStandalone.libs.at.pcgamingfreaks.Updater.UpdateProviders.BaseOnlineProvider.connect(BaseOnlineProvider.java:91) ~[[结婚]MarriageMaster.jar:?]
        at at.pcgamingfreaks.MarriageMasterStandalone.libs.at.pcgamingfreaks.Updater.UpdateProviders.SpigotUpdateProvider.query(SpigotUpdateProvider.java:91) ~[[结婚]MarriageMaster.jar:?]
        at at.pcgamingfreaks.MarriageMasterStandalone.libs.at.pcgamingfreaks.Updater.Updater.query(Updater.java:336) ~[[结婚]MarriageMaster.jar:?]
        at at.pcgamingfreaks.MarriageMasterStandalone.libs.at.pcgamingfreaks.Updater.Updater.doUpdate(Updater.java:360) ~[[结婚]MarriageMaster.jar:?]
        at at.pcgamingfreaks.MarriageMasterStandalone.libs.at.pcgamingfreaks.Updater.Updater.doUpdate(Updater.java:381) ~[[结婚]MarriageMaster.jar:?]
        at at.pcgamingfreaks.MarriageMasterStandalone.libs.at.pcgamingfreaks.Updater.Updater.doUpdate(Updater.java:381) ~[[结婚]MarriageMaster.jar:?]
        at at.pcgamingfreaks.MarriageMasterStandalone.libs.at.pcgamingfreaks.Updater.Updater.lambda$update$0(Updater.java:319) ~[[结婚]MarriageMaster.jar:?]
        at java.lang.Thread.run(Thread.java:1623) ~[?:?]
[17:53:46 INFO]: 出现错误！请查看控制台。

**Comment by GeorgH93** [comment]
Looks like something prevents your system from contacting `https://api.spiget.org/v2/resources/`. Are you sure that you have internet access? In order for the plugin to even check spigot checking for updates on dev bukkit and github must have also failed before, is there a log entry indicating that?

**Comment by aml2023529** [comment]
Yes I can network normally, I'm not sure why this firewall I have turned him off also can not detect updates properly

**Comment by aml2023529** [comment]
I have not moved him on the version is normal can run detection updates
