### ISSUE TITLE
plugin disabled, it doesnt work

### ISSUE THREAD

**Issue by szelongyau** [GeorgH93/MarriageMaster#324]
I know it is not the problem of the plugin but my server is 1.20.1, purpur server.
As i remembered the plugin worked on my server before (i havent use the function yet)
But now, the plugin doesnt work suddenly, i type /marry (it shows nothing)
It means the plugin was disabled , may i know what cann i do for this problem?
i have tried the lastest version too.

**Comment by GeorgH93** [comment]
Can you please share your servers log file with me?

**Comment by TheDeafCreeper** [comment]
@GeorgH93 having the same issue

```
[01:44:10] [Server thread/INFO]: [MarriageMaster] Enabling MarriageMaster v2.7.6
[01:44:10] [Server thread/ERROR]: Error occurred while enabling MarriageMaster v2.7.6 (Is it up to date?)
java.lang.ExceptionInInitializerError: null
	at java.base/java.lang.Class.forName0(Native Method) ~[?:?]
	at java.base/java.lang.Class.forName(Class.java:534) ~[?:?]
	at java.base/java.lang.Class.forName(Class.java:513) ~[?:?]
	at io.papermc.reflectionrewriter.runtime.AbstractDefaultRulesReflectionProxy.forName(AbstractDefaultRulesReflectionProxy.java:68) ~[?:?]
	at io.papermc.paper.pluginremap.reflect.PaperReflectionHolder.forName(Unknown Source) ~[?:1.21.1-DEV-fed0a8a]
	at MarriageMaster.jar/at.pcgamingfreaks.MarriageMasterStandalone.libs.at.pcgamingfreaks.Bukkit.PlatformResolver.getClass(PlatformResolver.java:118) ~[MarriageMaster.jar:?]
	at MarriageMaster.jar/at.pcgamingfreaks.MarriageMasterStandalone.libs.at.pcgamingfreaks.Bukkit.PlatformResolver.createPlatformInstance(PlatformResolver.java:104) ~[MarriageMaster.jar:?]
	at MarriageMaster.jar/at.pcgamingfreaks.MarriageMasterStandalone.libs.at.pcgamingfreaks.Bukkit.PlatformResolver.createPlatformInstance(PlatformResolver.java:58) ~[MarriageMaster.jar:?]
	at MarriageMaster.jar/at.pcgamingfreaks.MarriageMasterStandalone.libs.at.pcgamingfreaks.Bukkit.Util.IUtils.<clinit>(IUtils.java:30) ~[MarriageMaster.jar:?]
	at MarriageMaster.jar/at.pcgamingfreaks.MarriageMasterStandalone.libs.at.pcgamingfreaks.Bukkit.Util.Utils.<clinit>(Utils.java:44) ~[MarriageMaster.jar:?]
	at MarriageMaster.jar/at.pcgamingfreaks.MarriageMasterStandalone.Bukkit.MarriageMaster.onEnable(MarriageMaster.java:94) ~[MarriageMaster.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:293) ~[?:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:204) ~[?:1.21.1-DEV-fed0a8a]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[?:1.21.1-DEV-fed0a8a]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[?:?]
	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:732) ~[?:1.21.1-DEV-fed0a8a]
	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:674) ~[?:1.21.1-DEV-fed0a8a]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:798) ~[?:1.21.1-DEV-fed0a8a]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:533) ~[?:1.21.1-DEV-fed0a8a]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:380) ~[?:1.21.1-DEV-fed0a8a]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1310) ~[?:1.21.1-DEV-fed0a8a]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:332) ~[?:1.21.1-DEV-fed0a8a]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "java.net.URL.openStream()" because the return value of "java.security.CodeSource.getLocation()" is null
	at MarriageMaster.jar/at.pcgamingfreaks.MarriageMasterStandalone.libs.at.pcgamingfreaks.Bukkit.NMSReflectionRemapped.findClass(NMSReflectionRemapped.java:81) ~[MarriageMaster.jar:?]
	at MarriageMaster.jar/at.pcgamingfreaks.MarriageMasterStandalone.libs.at.pcgamingfreaks.Bukkit.NMSReflectionRemapped.getNmsClass(NMSReflectionRemapped.java:108) ~[MarriageMaster.jar:?]
	at MarriageMaster.jar/at.pcgamingfreaks.MarriageMasterStandalone.libs.at.pcgamingfreaks.Bukkit.Util.Utils_Reflection.<clinit>(Utils_Reflection.java:37) ~[MarriageMaster.jar:?]
	... 23 more
[01:44:10] [Server thread/INFO]: [MarriageMaster] Disabling MarriageMaster v2.7.6
[01:44:10] [Server thread/INFO]: [MarriageMaster]  Marriage Master has been disabled.  :( 
```

Server Version:
```
Current Canvas Version: 1.21.1-DEV-fed0a8a (MC: 1.21.1)*
* You are running the latest version
Previous: git-Purpur-2119 (MC: 1.20.4)
```

([Canvas](https://github.com/CraftCanvasMC/Canvas) is a Purpur fork)

**Comment by TheDeafCreeper** [comment]
wait I just realized this issue was for 1.20.1 not 1.21.1, may as well use it though.
