### ISSUE TITLE
Marry gift doesn't work? 1.20.6

### ISSUE THREAD

**Issue by LMRig** [GeorgH93/MarriageMaster#336]
### Help request

Is it a known problem? Getting this error:
`[18:44:10 INFO]: LMRig issued server command: /marry gift

[18:44:10 WARN]: [MarriageMaster] Unhandled exception executing command 'marry gift' in plugin MarriageMaster v2.7.5
at.pcgf.libs.com.google.gson.JsonIOException: Failed making field 'java.util.Optional#value' accessible; either increase its visibility or write a custom TypeAdapter for its declaring type.
	at PCGF_PluginLib-1.0.39.6-SNAPSHOT.jar/at.pcgf.libs.com.google.gson.internal.reflect.ReflectionHelper.makeAccessible(ReflectionHelper.java:38) ~[PCGF_PluginLib-1.0.39.6-SNAPSHOT.jar:?]
	at PCGF_PluginLib-1.0.39.6-SNAPSHOT.jar/at.pcgf.libs.com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:286) ~[PCGF_PluginLib-1.0.39.6-SNAPSHOT.jar:?]
	at PCGF_PluginLib-1.0.39.6-SNAPSHOT.jar/at.pcgf.libs.com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:130) ~[PCGF_PluginLib-1.0.39.6-SNAPSHOT.jar:?]
	at PCGF_PluginLib-1.0.39.6-SNAPSHOT.jar/at.pcgf.libs.com.google.gson.Gson.getAdapter(Gson.java:556) ~[PCGF_PluginLib-1.0.39.6-SNAPSHOT.jar:?]
	at PCGF_PluginLib-1.0.39.6-SNAPSHOT.jar/at.pcgf.libs.com.google.gson.internal.bind.MapTypeAdapterFactory.create(MapTypeAdapterFactory.java:125) ~[PCGF_PluginLib-1.0.39.6-SNAPSHOT.jar:?]
	at PCGF_PluginLib-1.0.39.6-SNAPSHOT.jar/at.pcgf.libs.com.google.gson.Gson.getAdapter(Gson.java:556) ~[PCGF_PluginLib-1.0.39.6-SNAPSHOT.jar:?]
	at PCGF_PluginLib-1.0.39.6-SNAPSHOT.jar/at.pcgf.libs.com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:160) ~[PCGF_PluginLib-1.0.39.6-SNAPSHOT.jar:?]
	at PCGF_PluginLib-1.0.39.6-SNAPSHOT.jar/at.pcgf.libs.com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:294) ~[PCGF_PluginLib-1.0.39.6-SNAPSHOT.jar:?]
	at PCGF_PluginLib-1.0.39.6-SNAPSHOT.jar/at.pcgf.libs.com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:130) ~[PCGF_PluginLib-1.0.39.6-SNAPSHOT.jar:?]
	at PCGF_PluginLib-1.0.39.6-SNAPSHOT.jar/at.pcgf.libs.com.google.gson.Gson.getAdapter(Gson.java:556) ~[PCGF_PluginLib-1.0.39.6-SNAPSHOT.jar:?]
	at PCGF_PluginLib-1.0.39.6-SNAPSHOT.jar/at.pcgf.libs.com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:160) ~[PCGF_PluginLib-1.0.39.6-SNAPSHOT.jar:?]
	at PCGF_PluginLib-1.0.39.6-SNAPSHOT.jar/at.pcgf.libs.com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:294) ~[PCGF_PluginLib-1.0.39.6-SNAPSHOT.jar:?]
	at PCGF_PluginLib-1.0.39.6-SNAPSHOT.jar/at.pcgf.libs.com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:130) ~[PCGF_PluginLib-1.0.39.6-SNAPSHOT.jar:?]
	at PCGF_PluginLib-1.0.39.6-SNAPSHOT.jar/at.pcgf.libs.com.google.gson.Gson.getAdapter(Gson.java:556) ~[PCGF_PluginLib-1.0.39.6-SNAPSHOT.jar:?]
	at PCGF_PluginLib-1.0.39.6-SNAPSHOT.jar/at.pcgf.libs.com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:160) ~[PCGF_PluginLib-1.0.39.6-SNAPSHOT.jar:?]
	at PCGF_PluginLib-1.0.39.6-SNAPSHOT.jar/at.pcgf.libs.com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:294) ~[PCGF_PluginLib-1.0.39.6-SNAPSHOT.jar:?]
	at PCGF_PluginLib-1.0.39.6-SNAPSHOT.jar/at.pcgf.libs.com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:130) ~[PCGF_PluginLib-1.0.39.6-SNAPSHOT.jar:?]
	at PCGF_PluginLib-1.0.39.6-SNAPSHOT.jar/at.pcgf.libs.com.google.gson.Gson.getAdapter(Gson.java:556) ~[PCGF_PluginLib-1.0.39.6-SNAPSHOT.jar:?]
	at PCGF_PluginLib-1.0.39.6-SNAPSHOT.jar/at.pcgf.libs.com.google.gson.Gson.toJson(Gson.java:834) ~[PCGF_PluginLib-1.0.39.6-SNAPSHOT.jar:?]
	at PCGF_PluginLib-1.0.39.6-SNAPSHOT.jar/at.pcgf.libs.com.google.gson.Gson.toJson(Gson.java:812) ~[PCGF_PluginLib-1.0.39.6-SNAPSHOT.jar:?]
	at PCGF_PluginLib-1.0.39.6-SNAPSHOT.jar/at.pcgf.libs.com.google.gson.Gson.toJson(Gson.java:759) ~[PCGF_PluginLib-1.0.39.6-SNAPSHOT.jar:?]
	at PCGF_PluginLib-1.0.39.6-SNAPSHOT.jar/at.pcgf.libs.com.google.gson.Gson.toJson(Gson.java:736) ~[PCGF_PluginLib-1.0.39.6-SNAPSHOT.jar:?]
	at PCGF_PluginLib-1.0.39.6-SNAPSHOT.jar/at.pcgamingfreaks.Bukkit.Util.InventoryUtils_1_20_R4_Paper.convertItemStackToJson(InventoryUtils_1_20_R4_Paper.java:47) ~[PCGF_PluginLib-1.0.39.6-SNAPSHOT.jar:?]
	at PCGF_PluginLib-1.0.39.6-SNAPSHOT.jar/at.pcgamingfreaks.Bukkit.Util.InventoryUtils.convertItemStackToJson(InventoryUtils.java:48) ~[PCGF_PluginLib-1.0.39.6-SNAPSHOT.jar:?]
	at PCGF_PluginLib-1.0.39.6-SNAPSHOT.jar/at.pcgamingfreaks.Bukkit.Message.Placeholder.Processors.Wrappers.ItemStackWrapper.getItemMetadata(ItemStackWrapper.java:66) ~[PCGF_PluginLib-1.0.39.6-SNAPSHOT.jar:?]
	at PCGF_PluginLib-1.0.39.6-SNAPSHOT.jar/at.pcgamingfreaks.Bukkit.Message.Placeholder.Processors.ItemMetadataPlaceholderProcessor.process(ItemMetadataPlaceholderProcessor.java:46) ~[PCGF_PluginLib-1.0.39.6-SNAPSHOT.jar:?]
	at PCGF_PluginLib-1.0.39.6-SNAPSHOT.jar/at.pcgamingfreaks.Message.Placeholder.StringPlaceholderJsonEscapeProcessor.process(StringPlaceholderJsonEscapeProcessor.java:43) ~[PCGF_PluginLib-1.0.39.6-SNAPSHOT.jar:?]
	at PCGF_PluginLib-1.0.39.6-SNAPSHOT.jar/at.pcgamingfreaks.Message.Placeholder.StringPlaceholderEngine.processPlaceholders(StringPlaceholderEngine.java:126) ~[PCGF_PluginLib-1.0.39.6-SNAPSHOT.jar:?]
	at PCGF_PluginLib-1.0.39.6-SNAPSHOT.jar/at.pcgamingfreaks.Message.Placeholder.MessageComponentPlaceholderEngine.processPlaceholders(MessageComponentPlaceholderEngine.java:113) ~[PCGF_PluginLib-1.0.39.6-SNAPSHOT.jar:?]
	at PCGF_PluginLib-1.0.39.6-SNAPSHOT.jar/at.pcgamingfreaks.Message.PlaceholderHandler.format(PlaceholderHandler.java:111) ~[PCGF_PluginLib-1.0.39.6-SNAPSHOT.jar:?]
	at PCGF_PluginLib-1.0.39.6-SNAPSHOT.jar/at.pcgamingfreaks.Message.Message.prepareMessage(Message.java:331) ~[PCGF_PluginLib-1.0.39.6-SNAPSHOT.jar:?]
	at PCGF_PluginLib-1.0.39.6-SNAPSHOT.jar/at.pcgamingfreaks.Bukkit.Message.Message.send(Message.java:245) ~[PCGF_PluginLib-1.0.39.6-SNAPSHOT.jar:?]
	at MarriageMaster.jar/at.pcgamingfreaks.MarriageMaster.Bukkit.Commands.GiftCommand.executeGift(GiftCommand.java:231) ~[MarriageMaster.jar:?]
	at MarriageMaster.jar/at.pcgamingfreaks.MarriageMaster.Bukkit.Commands.GiftCommand.execute(GiftCommand.java:191) ~[MarriageMaster.jar:?]
	at MarriageMaster.jar/at.pcgamingfreaks.MarriageMaster.Bukkit.Commands.GiftCommand.execute(GiftCommand.java:52) ~[MarriageMaster.jar:?]
	at MarriageMaster.jar/at.pcgamingfreaks.MarriageMaster.Bukkit.API.MarryCommand.doExecute(MarryCommand.java:156) ~[MarriageMaster.jar:?]
	at MarriageMaster.jar/at.pcgamingfreaks.MarriageMaster.Bukkit.API.MarryCommand.doExecute(MarryCommand.java:38) ~[MarriageMaster.jar:?]
	at MarriageMaster.jar/at.pcgamingfreaks.MarriageMaster.Bukkit.Commands.CommandManagerImplementation.onCommand(CommandManagerImplementation.java:182) ~[MarriageMaster.jar:?]
	at PCGF_PluginLib-1.0.39.6-SNAPSHOT.jar/at.pcgamingfreaks.Bukkit.Command.RegisterablePluginCommand.execute(RegisterablePluginCommand.java:157) ~[PCGF_PluginLib-1.0.39.6-SNAPSHOT.jar:?]
	at io.papermc.paper.command.brigadier.bukkit.BukkitCommandNode$BukkitBrigCommand.run(BukkitCommandNode.java:91) ~[paper-1.20.6.jar:1.20.6-142-3889ffb]
	at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73) ~[brigadier-1.2.9.jar:?]
	at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:31) ~[paper-1.20.6.jar:1.20.6-142-3889ffb]
	at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:19) ~[paper-1.20.6.jar:1.20.6-142-3889ffb]
	at net.minecraft.commands.execution.UnboundEntryAction.lambda$bind$0(UnboundEntryAction.java:8) ~[paper-1.20.6.jar:1.20.6-142-3889ffb]
	at net.minecraft.commands.execution.CommandQueueEntry.execute(CommandQueueEntry.java:5) ~[paper-1.20.6.jar:1.20.6-142-3889ffb]
	at net.minecraft.commands.execution.ExecutionContext.runCommandQueue(ExecutionContext.java:103) ~[paper-1.20.6.jar:1.20.6-142-3889ffb]
	at net.minecraft.commands.Commands.executeCommandInContext(Commands.java:448) ~[paper-1.20.6.jar:1.20.6-142-3889ffb]
	at net.minecraft.commands.Commands.performCommand(Commands.java:355) ~[paper-1.20.6.jar:1.20.6-142-3889ffb]
	at net.minecraft.commands.Commands.performCommand(Commands.java:342) ~[paper-1.20.6.jar:1.20.6-142-3889ffb]
	at net.minecraft.commands.Commands.performCommand(Commands.java:337) ~[paper-1.20.6.jar:1.20.6-142-3889ffb]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.performUnsignedChatCommand(ServerGamePacketListenerImpl.java:2202) ~[paper-1.20.6.jar:1.20.6-142-3889ffb]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$14(ServerGamePacketListenerImpl.java:2176) ~[paper-1.20.6.jar:1.20.6-142-3889ffb]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.6.jar:1.20.6-142-3889ffb]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[paper-1.20.6.jar:1.20.6-142-3889ffb]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[paper-1.20.6.jar:1.20.6-142-3889ffb]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1511) ~[paper-1.20.6.jar:1.20.6-142-3889ffb]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:195) ~[paper-1.20.6.jar:1.20.6-142-3889ffb]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[paper-1.20.6.jar:1.20.6-142-3889ffb]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1488) ~[paper-1.20.6.jar:1.20.6-142-3889ffb]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1411) ~[paper-1.20.6.jar:1.20.6-142-3889ffb]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[paper-1.20.6.jar:1.20.6-142-3889ffb]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1377) ~[paper-1.20.6.jar:1.20.6-142-3889ffb]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1238) ~[paper-1.20.6.jar:1.20.6-142-3889ffb]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[paper-1.20.6.jar:1.20.6-142-3889ffb]
	at java.base/java.lang.Thread.run(Unknown Source) ~[?:?]
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make field private final java.lang.Object java.util.Optional.value accessible: module java.base does not "opens java.util" to unnamed module @406ce263
	at java.base/java.lang.reflect.AccessibleObject.throwInaccessibleObjectException(Unknown Source) ~[?:?]
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(Unknown Source) ~[?:?]
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(Unknown Source) ~[?:?]
	at java.base/java.lang.reflect.Field.checkCanSetAccessible(Unknown Source) ~[?:?]
	at java.base/java.lang.reflect.Field.setAccessible(Unknown Source) ~[?:?]
	at PCGF_PluginLib-1.0.39.6-SNAPSHOT.jar/at.pcgf.libs.com.google.gson.internal.reflect.ReflectionHelper.makeAccessible(ReflectionHelper.java:35) ~[PCGF_PluginLib-1.0.39.6-SNAPSHOT.jar:?]

	... 64 more`

**Comment by GeorgH93** [comment]
Should be fixed with newest release.
