### ISSUE TITLE
Zip file closed

### ISSUE THREAD

**Issue by TheIntelloBox** [GeorgH93/MarriageMaster#35]
Using latest dev builc, all plugins have this error:

Caused by: java.lang.IllegalStateException: zip file closed
	at java.util.zip.ZipFile.ensureOpen(ZipFile.java:669) ~[?:1.8.0_72]
	at java.util.zip.ZipFile.getEntry(ZipFile.java:309) ~[?:1.8.0_72]
	at java.util.jar.JarFile.getEntry(JarFile.java:240) ~[?:1.8.0_72]
	at java.util.jar.JarFile.getJarEntry(JarFile.java:223) ~[?:1.8.0_72]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:120) ~[patched_1.12.2.jar:git-Paper-1500]
	at org.bukkit.plugin.java.JavaPluginLoader.getClassByName(JavaPluginLoader.java:189) ~[patched_1.12.2.jar:git-Paper-1500]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:115) ~[patched_1.12.2.jar:git-Paper-1500]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:104) ~[patched_1.12.2.jar:git-Paper-1500]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_72]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_72]

**Comment by GeorgH93** [comment]
Could you please provide me with the complete server log.

**Comment by TheIntelloBox** [comment]
https://paste.ee/p/iI4Nb

**Comment by GeorgH93** [comment]
Please try if this build resolves the issue for you: https://ci.pcgamingfreaks.at/job/MarriageMaster%20V2/39/artifact/target/MarriageMaster-2.0-RC2-SNAPSHOT.jar

**Comment by TheIntelloBox** [comment]
Fantastic, thanks. :D
