### ISSUE TITLE
Problem with the Placeholder in DeluxeChat

### ISSUE THREAD

**Issue by DinoTK** [GeorgH93/MarriageMaster#42]
Hi! 
I've this problem when I start my server and when I put a player as priest. Running the MarriageMaster V2.0+Latest version of PluginLib+DeluxeChat btw. 
Note: I already downloaded the marriagemaster placeholder ecloud.

This message appears when the server start and the placeholders is not showing in deluxechat:
```
[16:16:42 INFO]: [MarriageMaster] Enabling MarriageMaster v2.0-RC2-SNAPSHOT-T20190208161527
[16:16:42 INFO]: [MarriageMaster] File "/config.yml" extracted successfully!
[16:16:42 INFO]: [MarriageMaster] Config file successfully loaded.
[16:16:42 INFO]: [MarriageMaster] No compatible backpack plugin found.
[16:16:42 INFO]: [MarriageMaster] File "/lang/en.yml" extracted successfully!
[16:16:42 INFO]: [MarriageMaster] Language file successfully loaded.
[16:16:42 INFO]: MarriageMaster-Connection-Pool - is starting.
[16:16:42 INFO]: [MarriageMaster] Loading marriages ...
[16:16:42 INFO]: [MarriageMaster] Marriages loaded
[16:16:42 INFO]: [MarriageMaster] Loading priests ...
[16:16:42 INFO]: [MarriageMaster] Priests loaded
[16:16:42 INFO]: [MarriageMaster] Loading players ...
[16:16:42 INFO]: [MarriageMaster] Players loaded
[16:16:42 INFO]: [MarriageMaster] Writing marriages into cache ...
[16:16:42 INFO]: [MarriageMaster] Marriages loaded into cache
[16:16:42 INFO]: [MarriageMaster] DeluxeChat placeholder hook failed to registered!
[16:16:42 INFO]: [MarriageMaster]  Marriage Master has been enabled!  :)
```

And this message appears when I do /marry setpriest <player>:
```
[16:40:49 INFO]: Louv issued server command: /marry setpriest dinotk
[16:40:49 INFO]:
Query: INSERT OR REPLACE INTO `marry_priests` (`player_id`) VALUE (?);
Data: [2]
[16:40:49 WARN]: org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (near "VALUE": syntax error)
[16:40:49 WARN]:        at org.sqlite.core.DB.newSQLException(DB.java:941)
[16:40:49 WARN]:        at org.sqlite.core.DB.newSQLException(DB.java:953)
[16:40:49 WARN]:        at org.sqlite.core.DB.throwex(DB.java:918)
[16:40:49 WARN]:        at org.sqlite.core.NativeDB.prepare_utf8(Native Method)
[16:40:49 WARN]:        at org.sqlite.core.NativeDB.prepare(NativeDB.java:134)
[16:40:49 WARN]:        at org.sqlite.core.DB.prepare(DB.java:257)
[16:40:49 WARN]:        at org.sqlite.core.CorePreparedStatement.<init>(CorePreparedStatement.java:47)
[16:40:49 WARN]:        at org.sqlite.jdbc3.JDBC3PreparedStatement.<init>(JDBC3PreparedStatement.java:30)
[16:40:49 WARN]:        at org.sqlite.jdbc4.JDBC4PreparedStatement.<init>(JDBC4PreparedStatement.java:19)
[16:40:49 WARN]:        at org.sqlite.jdbc4.JDBC4Connection.prepareStatement(JDBC4Connection.java:35)
[16:40:49 WARN]:        at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:241)
[16:40:49 WARN]:        at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:205)
[16:40:49 WARN]:        at com.zaxxer.hikari.proxy.ConnectionProxy.prepareStatement(ConnectionProxy.java:265)
[16:40:49 WARN]:        at com.zaxxer.hikari.proxy.HikariConnectionProxy.prepareStatement(HikariConnectionProxy.java)
[16:40:49 WARN]:        at at.pcgamingfreaks.Database.DBTools.runStatement(DBTools.java:553)
[16:40:49 WARN]:        at at.pcgamingfreaks.Database.DBTools.runStatementWithoutException(DBTools.java:572)
[16:40:49 WARN]:        at at.pcgamingfreaks.MarriageMaster.Database.DbElementStatementWithKeyRunnable.runStatement(DbElementStatementWithKeyRunnable.java:48)
[16:40:49 WARN]:        at at.pcgamingfreaks.MarriageMaster.Database.DbElementStatementRunnable.run(DbElementStatementRunnable.java:51)
[16:40:49 WARN]:        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:81)
[16:40:49 WARN]:        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
[16:40:49 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[16:40:49 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[16:40:49 WARN]:        at java.lang.Thread.run(Unknown Source)
```

And the same when I reload MarriageMaster:
```
>marry reload
[16:19:52 INFO]: Reloading ...
[16:19:52 INFO]: MarriageMaster-Connection-Pool - is closing down.
[16:19:52 INFO]: [MarriageMaster] Cleaning database cache.
[16:19:52 INFO]: [MarriageMaster] Database cache cleaned.
[16:19:52 INFO]: [MarriageMaster] Config file successfully loaded.
[16:19:52 INFO]: [MarriageMaster] Language file successfully loaded.
[16:19:52 INFO]: MarriageMaster-Connection-Pool - is starting.
[16:19:52 INFO]: [MarriageMaster] Loading marriages ...
[16:19:52 INFO]: [MarriageMaster] Marriages loaded
[16:19:52 INFO]: [MarriageMaster] Loading priests ...
[16:19:52 INFO]: [MarriageMaster] Priests loaded
[16:19:52 INFO]: [MarriageMaster] Loading players ...
[16:19:52 INFO]: [MarriageMaster] Players loaded
[16:19:52 INFO]: [MarriageMaster] Writing marriages into cache ...
[16:19:52 INFO]: [MarriageMaster] Marriages loaded into cache
[16:19:52 INFO]: [MarriageMaster] DeluxeChat placeholder hook failed to registered!
[16:19:52 INFO]: Reloaded!
[16:19:52 INFO]: [MarriageMaster] Loading homes ...
[16:19:52 INFO]: [MarriageMaster] Homes loaded
```

**Comment by GeorgH93** [comment]
Marriage Master V2.0 provides it's own placeholders, there is no need to install anything else for it. The PAPI ecloud extension is not created by me and seems to target Marriage Master V1.X builds.

This build should fix the setpriest command: https://ci.pcgamingfreaks.at/job/MarriageMaster%20V2/48/artifact/target/MarriageMaster-2.0-RC2-SNAPSHOT.jar

**Comment by DinoTK** [comment]
Thanks! It worked very well
