### ISSUE TITLE
Error enabling most recent builds. Integration with Minepacks?

### ISSUE THREAD

**Issue by NABrr** [GeorgH93/MarriageMaster#54]
`[17:45:48] [Server thread/INFO]: [MarriageMaster] Enabling MarriageMaster v1.31.13
[17:45:48] [Server thread/INFO]: [MarriageMaster] Config Version: 28 => no update needed
[17:45:48] [Server thread/INFO]: [MarriageMaster] Config loaded
[17:45:48] [Server thread/INFO]: [MarriageMaster] Language Version: 19 => no update needed
[17:45:48] [Server thread/INFO]: [MarriageMaster] Checking for updates ...
[17:45:48] [Server thread/ERROR]: Error occurred while enabling MarriageMaster v1.31.13 (Is it up to date?)
java.lang.NoClassDefFoundError: at/pcgamingfreaks/Minepacks/Bukkit/API/MinepacksPlugin
	at at.pcgamingfreaks.MarriageMaster.Bukkit.Minepacks.MinepacksIntegration.<init>(MinepacksIntegration.java:33) ~[?:?]
	at at.pcgamingfreaks.MarriageMaster.Bukkit.Minepacks.MinePacksIntegrationBase.getIntegration(MinePacksIntegrationBase.java:51) ~[?:?]
	at at.pcgamingfreaks.MarriageMaster.Bukkit.MarriageMaster.load(MarriageMaster.java:113) ~[?:?]
	at at.pcgamingfreaks.MarriageMaster.Bukkit.MarriageMaster.onEnable(MarriageMaster.java:76) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:254) ~[patched_1.13.2.jar:git-Paper-561]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:326) ~[patched_1.13.2.jar:git-Paper-561]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:406) ~[patched_1.13.2.jar:git-Paper-561]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:443) ~[patched_1.13.2.jar:git-Paper-561]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:357) ~[patched_1.13.2.jar:git-Paper-561]
	at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:608) ~[patched_1.13.2.jar:git-Paper-561]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:570) ~[patched_1.13.2.jar:git-Paper-561]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:431) ~[patched_1.13.2.jar:git-Paper-561]
	at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:316) ~[patched_1.13.2.jar:git-Paper-561]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:786) ~[patched_1.13.2.jar:git-Paper-561]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: java.lang.ClassNotFoundException: at.pcgamingfreaks.Minepacks.Bukkit.API.MinepacksPlugin
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_212]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:138) ~[patched_1.13.2.jar:git-Paper-561]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:84) ~[patched_1.13.2.jar:git-Paper-561]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_212]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_212]
	... 15 more
[17:45:48] [Server thread/INFO]: [MarriageMaster] Disabling MarriageMaster v1.31.13
[17:45:48] [Server thread/INFO]: [MarriageMaster] Checking for updates ...
[17:45:48] [Server thread/INFO]: [MarriageMaster] Marriage Master has been disabled.
`

**Comment by GeorgH93** [comment]
Can you please provide me the output of "/version" and "/version minepacks"

**Comment by NABrr** [comment]
- Paper version: git-Paper-561
- API version: 1.13.2-R0.1-Snapshot
- 64 Versions Behind

MinePacks version 1.19.2

**Comment by NABrr** [comment]
Versions prior to these operated fine together.

**Comment by GeorgH93** [comment]
Thanks for the report. This should fix it: https://ci.pcgamingfreaks.at/job/MarriageMaster/78/artifact/target/MarriageMaster-1.31.15.jar

**Comment by NABrr** [comment]
Apologies for not getting back. It did indeed fix the issue. Much thanks.
