### ISSUE TITLE
PAPI Placeholders break the entirety of PAPI

### ISSUE THREAD

**Issue by CaptainAmpersand** [GeorgH93/MarriageMaster#68]
### Information
**Environment information**
*Plugin + server version info*:

```
##### Start Marriage Master version info #####
Marriage Master: 2.0.2-Release
Server: git-Paper-133 (MC: 1.14.3)
#####  End Marriage Master version info  #####
(That's a kind of cool command props to you lol)
```

*Online mode*: Yes

*BungeeCord*: No

**Server/crash log**

```
[01:23:01] [Server thread/INFO]: Ampersand issued server command: /papi ecloud download MarriageMaster
[01:23:01] [Server thread/INFO]: [PlaceholderAPI] Attempting download of expansion: MarriageMaster by user: Ampersand from url: http://api.extendedclip.com/media/Expansion-MarriageMaster_3WNs7dj.jar
[01:23:01] [Server thread/INFO]: [PlaceholderAPI] Fetching available expansion information...
[01:23:01] [Craft Scheduler Thread - 506/INFO]: [PlaceholderAPI] Download of expansion: MarriageMaster complete!
[01:23:03] [Craft Scheduler Thread - 495/INFO]: [PlaceholderAPI] 152 placeholder expansions are available on the cloud.
[01:23:04] [Server thread/INFO]: Ampersand issued server command: /papi reload
[01:23:04] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'papi' in plugin PlaceholderAPI v2.10.3
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.14.3.jar:git-Paper-133]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.14.3.jar:git-Paper-133]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:739) ~[patched_1.14.3.jar:git-Paper-133]
	at net.minecraft.server.v1_14_R1.PlayerConnection.handleCommand(PlayerConnection.java:1837) ~[patched_1.14.3.jar:git-Paper-133]
	at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1645) ~[patched_1.14.3.jar:git-Paper-133]
	at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.14.3.jar:git-Paper-133]
	at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.14.3.jar:git-Paper-133]
	at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:18) ~[patched_1.14.3.jar:git-Paper-133]
	at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) ~[patched_1.14.3.jar:git-Paper-133]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:127) ~[patched_1.14.3.jar:git-Paper-133]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.14.3.jar:git-Paper-133]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:105) ~[patched_1.14.3.jar:git-Paper-133]
	at net.minecraft.server.v1_14_R1.MinecraftServer.aW(MinecraftServer.java:1002) ~[patched_1.14.3.jar:git-Paper-133]
	at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:995) ~[patched_1.14.3.jar:git-Paper-133]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:115) ~[patched_1.14.3.jar:git-Paper-133]
	at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:979) ~[patched_1.14.3.jar:git-Paper-133]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:912) ~[patched_1.14.3.jar:git-Paper-133]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
Caused by: java.lang.ClassCastException: at.pcgamingfreaks.MarriageMasterStandalone.Bukkit.MarriageMaster cannot be cast to at.pcgamingfreaks.MarriageMaster.Bukkit.MarriageMaster
	at com.extendedclip.papi.expansion.marriagemaster.MarriageMasterExpansion.register(MarriageMasterExpansion.java:46) ~[?:?]
	at me.clip.placeholderapi.expansion.ExpansionManager.registerExpansion(ExpansionManager.java:105) ~[?:?]
	at me.clip.placeholderapi.expansion.ExpansionManager.registerAllExpansions(ExpansionManager.java:154) ~[?:?]
	at me.clip.placeholderapi.PlaceholderAPIPlugin.reloadConf(PlaceholderAPIPlugin.java:176) ~[?:?]
	at me.clip.placeholderapi.commands.PlaceholderAPICommands.onCommand(PlaceholderAPICommands.java:226) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.14.3.jar:git-Paper-133]
	... 17 more
```

**Plugin config (optional)**

```
N/A, just the latest version broke PlaceholderAPI placeholders. It's just this plugin.
```

### Details
**Description**  
This release of MarriageMaster broke the Placeholders, error is above.

**Steps to reproduce**  
N/A -- Just update the plugin, update PlaceholderAPI, PAPI version 2.10.3, and it is broken.

**Expected behavior**  
The server is able to properly show all placeholders relating to MarriageMaster. 

**Other information** (e.g. detailed explanation, related issues, suggestions how to fix, links for us to have context, screenshots, etc.)
N/A

**Comment by GeorgH93** [comment]
Please remove the MarriageMaster ecloud extension, Marriage Master v2 provides the placeholders directly.
