### ISSUE TITLE
Error on plugin startup

### ISSUE THREAD

**Issue by MithrandirCraft** [GeorgH93/MarriageMaster#69]
*Plugin + server version info*: 
Spigot 1.13.2
MM 2.0.3

*Online mode*: no

*BungeeCord*: yes

**Server/crash log**
https://pastebin.com/YYdN1hVh

Error occurs on startup.

**Comment by GeorgH93** [comment]
That's a strange one, it looks like your priests table contains the key 0 more than once. Which should not be possible.
Could you please dump me that table?

**Comment by MithrandirCraft** [comment]
Yez. brb

**Comment by MithrandirCraft** [comment]
![imagen](https://user-images.githubusercontent.com/6623704/61498267-e3140380-a9c2-11e9-80ba-486efa2c9af4.png)
Is this ok? It's all of them.

**Comment by MithrandirCraft** [comment]
It looks messed up. Maybe I should delete it xD

**Comment by GeorgH93** [comment]
If you delete the `player_id` column and then rename the `priest_id` column to `player_id` it should work when you reload the plugin.

**Comment by MithrandirCraft** [comment]
Will do then. Let's see how it goes.

**Comment by GeorgH93** [comment]
I have just released an update that should prevent this from happening.
If you have renamed the column already make sure to update all of your config files with v2.0.3.

Alternative with v2.0.4:
* Delete the `player_id` column
* Edit already upgraded config files by adding the `Database.SQL.Tables.Fields.PriestID` key with the value `priest_id`.

**Comment by MithrandirCraft** [comment]
New error: https://gist.github.com/MithrandirCraft/3b9e977a538cf63c8d0c3d85c2debeae

I don't understand what you want me to edit in the config, you want me to change a table name?

**Comment by MithrandirCraft** [comment]
oops, closed by mistake

**Comment by GeorgH93** [comment]
Could you please share your config file with me?

**Comment by MithrandirCraft** [comment]
Current config: https://gist.github.com/MithrandirCraft/a38960dc43f7a5eb50d05543dbe1e789

I seem to have other issues I haven't checked. Players tell me the whole system simply doesn't work, which would be comprehensible if there are still database connection issues.

**Comment by GeorgH93** [comment]
Please run this query `DELETE FROM marry_home WHERE marry_id NOT IN (SELECT marry_partners.marry_id FROM marry_partners);` on your database. It should cleanup the homes table so that it can be converted to the new format when you restart your server.

**Comment by MithrandirCraft** [comment]
The table name for homes wasn't the same as in config. I've corrected this, we'll see how it goes from now.

**Comment by MithrandirCraft** [comment]
I deleted the whole marry_home table, since I still had issues... it seems like the plugin just can't generate it again.

**Comment by GeorgH93** [comment]
Please try this build: https://ci.pcgamingfreaks.at/job/MarriageMaster/lastSuccessfulBuild/artifact/artifacts/MarriageMaster-2.0.5-RC3-Release.jar
And in case it fails please provide me with the startup log.

**Comment by MithrandirCraft** [comment]
https://gist.github.com/MithrandirCraft/1fbfba3c3786f701c411d40454bf8ad1

**Comment by GeorgH93** [comment]
Please run this `SHOW CREATE TABLE hub.marry_partners;` query and send me the output.

**Comment by MithrandirCraft** [comment]
Ummm... like this?
![imagen](https://user-images.githubusercontent.com/6623704/61565521-8f182600-aa79-11e9-82cd-c948124309f1.png)
Sorry, I'm not very good at sql :P

**Comment by MithrandirCraft** [comment]
I don't know what the command you sent me does, but I'm assuming it may be Hub. instead of hub.

**Comment by MithrandirCraft** [comment]
Looks better.
![imagen](https://user-images.githubusercontent.com/6623704/61565669-0bab0480-aa7a-11e9-940b-f63c85d88c25.png)

**Comment by GeorgH93** [comment]
Thanks.
The table uses the MyISAM engine which does not support foreign keys. That resolves the question around why the other table is not being created correctly.

Please run these query's to convert the tables to InnoDB:
```
ALTER TABLE marry_players ENGINE = InnoDB;
ALTER TABLE marry_priests ENGINE = InnoDB;
ALTER TABLE marry_partners ENGINE = InnoDB;
```
and try to restart/reload the plugin afterwards.

**Comment by comonier** [comment]
all my plugins have problems with this latest or oldest builds, some error in bukkit communications.

`[02:25:42] [Server thread/INFO]: [FeatherBoard] An error occurred while initializing placeholders code=marriagemaster
[02:25:42] [Server thread/INFO]: [FeatherBoard] The placeholders have been disabled for use.
[02:25:42] [Server thread/WARN]: java.lang.ClassCastException: at.pcgamingfreaks.MarriageMasterStandalone.Bukkit.MarriageMaster cannot be cast to at.pcgamingfreaks.MarriageMaster.Bukkit.MarriageMaster
[02:25:42] [Server thread/WARN]: 	at be.maximvdw.placeholdercore.placeholders.MarriageMasterPlaceholderPack.onEnable(MarriageMasterPlaceholderPack.java:67)
[02:25:42] [Server thread/WARN]: 	at be.maximvdw.featherboard.F.registerPlaceHolder(F.java:83)
[02:25:42] [Server thread/WARN]: 	at be.maximvdw.featherboard.bp.a(bp.java:101)
[02:25:42] [Server thread/WARN]: 	at be.maximvdw.featherboard.bp.a(bp.java:164)
[02:25:42] [Server thread/WARN]: 	at be.maximvdw.featherboard.bp.g(bp.java:64)
[02:25:42] [Server thread/WARN]: 	at be.maximvdw.featherboard.a5.b(a5.java:32)
[02:25:42] [Server thread/WARN]: 	at be.maximvdw.featherboard.a5.<init>(a5.java:18)
[02:25:42] [Server thread/WARN]: 	at be.maximvdw.featherboard.FeatherBoard.m(FeatherBoard.java:36)
[02:25:42] [Server thread/WARN]: 	at be.maximvdw.featherboard.P.a(P.java:38)
[02:25:42] [Server thread/WARN]: 	at be.maximvdw.featherboard.P.onEnable(P.java:72)
[02:25:42] [Server thread/WARN]: 	at be.maximvdw.featherboard.FeatherBoard.onEnable(FeatherBoard.java:96)
[02:25:42] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[02:25:42] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338)
[02:25:42] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:420)
[02:25:42] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:467)
[02:25:42] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:381)
[02:25:42] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:464)
[02:25:42] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:282)
[02:25:42] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:859)
[02:25:42] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
[02:25:43] [Server thread/INFO]: [FeatherBoard] Checking for placeholder updates ...
[02:25:43] [Server thread/INFO]: [FeatherBoard] Loaded 5548 of the 5552 placholders
[02:25:43] [Server thread/INFO]: [MVdWPlaceholderAPI] Hooked into MVdW plugin: FeatherBoard
[02:25:44] [Server thread/INFO]: [FeatherBoard] Loading custom effect 'example1' ...
[02:25:44] [Server thread/INFO]: [FeatherBoard] Creating new custom effect: example1
[02:25:44] [Server thread/INFO]: [FeatherBoard] Loading custom effect 'example2' ...
[02:25:44] [Server thread/INFO]: [FeatherBoard] Creating new custom effect: example2
[02:25:44] [Server thread/INFO]: [FeatherBoard] Loading custom effect 'example3' ...
[02:25:44] [Server thread/INFO]: [FeatherBoard] Creating new custom effect: example3
[02:25:45] [Server thread/INFO]: [FeatherBoard] Using OPTIMAL as the update strategy
[02:25:45] [Server thread/INFO]: [FeatherBoard] Loading scoreboard 'benchmark' ...
[02:25:46] [Server thread/INFO]: [FeatherBoard] Loading scoreboard 'combat-scoreboard-example' ...
[02:25:46] [Server thread/INFO]: [FeatherBoard] Loading scoreboard 'default' ...
[02:25:46] [Server thread/INFO]: [FeatherBoard] Loading scoreboard 'mcmmo-levelup' ...
[02:25:46] [Server thread/INFO]: [FeatherBoard] Loading scoreboard 'towny-town-example' ...
[02:25:46] [Server thread/INFO]: [FeatherBoard] Added 'PERMISSION' as the default scoreboard assign method
[02:25:46] [Server thread/INFO]: [FeatherBoard] Generating metrics information ...
[02:25:47] [Server thread/INFO]: [FeatherBoard] Failed to check for an update on spigot.
[02:25:47] [Server thread/WARN]: java.io.IOException: Server returned HTTP response code: 521 for URL: https://api.spigotmc.org/legacy/update.php?resource=2691
[02:25:47] [Server thread/WARN]: 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
[02:25:47] [Server thread/WARN]: 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
[02:25:47] [Server thread/WARN]: 	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source)
[02:25:47] [Server thread/WARN]: 	at be.maximvdw.featherboard.cJ.g(cJ.java:40)
[02:25:47] [Server thread/WARN]: 	at be.maximvdw.featherboard.cJ.c(cJ.java:29)
[02:25:47] [Server thread/WARN]: 	at be.maximvdw.featherboard.FeatherBoard.f(FeatherBoard.java:18)
[02:25:47] [Server thread/WARN]: 	at be.maximvdw.featherboard.P.a(P.java:18)
[02:25:47] [Server thread/WARN]: 	at be.maximvdw.featherboard.P.onEnable(P.java:72)
[02:25:47] [Server thread/WARN]: 	at be.maximvdw.featherboard.FeatherBoard.onEnable(FeatherBoard.java:96)
[02:25:47] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[02:25:47] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338)
[02:25:47] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:420)
[02:25:47] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:467)
[02:25:47] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:381)
[02:25:47] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:464)
[02:25:47] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:282)
[02:25:47] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:859)
[02:25:47] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
[02:25:47] [Server thread/INFO]: [FeatherBoard] Your version is up to date!
[02:25:48] [Server thread/INFO]: [FeatherBoard] Toggle persistence is disabled!
[02:25:48] [Server thread/INFO]: [FeatherBoard] Adding command 'featherboard'`

`[02:25:51 INFO]: [UltimateChat] Enabling UltimateChat v1.8.9
[02:25:51 INFO]: [UltimateChat] All configurations loaded!
[02:25:51 INFO]: [UltimateChat] Language file loaded - Using: PT-BR
[02:25:51 INFO]: [UltimateChat] ProtocolLib found. Hooked.
[02:25:51 WARN]: java.lang.ClassCastException: at.pcgamingfreaks.MarriageMasterStandalone.Bukkit.MarriageMaster cannot be cast to at.pcgamingfreaks.MarriageMaster.Bukkit.MarriageMaster
[02:25:51 WARN]:        at br.net.fabiozumbi12.UltimateChat.Bukkit.UChat.onEnable(UChat.java:224)
[02:25:51 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[02:25:51 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338)
[02:25:51 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:420)
[02:25:51 WARN]:        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:467)
[02:25:51 WARN]:        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:381)
[02:25:51 WARN]:        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:464)
[02:25:51 WARN]:        at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:282)
[02:25:51 WARN]:        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:859)
[02:25:51 WARN]:        at java.lang.Thread.run(Unknown Source)
[02:25:51 INFO]: [UltimateChat] UltimateChat v1.8.9 disabled!`

`[02:25:51] [Server thread/INFO]: [UltimateChat] Enabling UltimateChat v1.8.9
[02:25:51] [Server thread/INFO]: [UltimateChat] All configurations loaded!
[02:25:51] [Server thread/INFO]: [UltimateChat] Language file loaded - Using: PT-BR
[02:25:51] [Server thread/INFO]: [UltimateChat] ProtocolLib found. Hooked.
[02:25:51] [Server thread/WARN]: java.lang.ClassCastException: at.pcgamingfreaks.MarriageMasterStandalone.Bukkit.MarriageMaster cannot be cast to at.pcgamingfreaks.MarriageMaster.Bukkit.MarriageMaster
[02:25:51] [Server thread/WARN]: 	at br.net.fabiozumbi12.UltimateChat.Bukkit.UChat.onEnable(UChat.java:224)
[02:25:51] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[02:25:51] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338)
[02:25:51] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:420)
[02:25:51] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:467)
[02:25:51] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:381)
[02:25:51] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:464)
[02:25:51] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:282)
[02:25:51] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:859)
[02:25:51] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
[02:25:51] [Server thread/INFO]: [UltimateChat] UltimateChat v1.8.9 disabled!`

**Comment by GeorgH93** [comment]
> 
> 
> all my plugins have problems with this latest or oldest builds, some error in bukkit communications.
> 
> `[02:25:42] [Server thread/INFO]: [FeatherBoard] An error occurred while initi ....

1. open the file `plugins/FeatherBoard/placeholders/placeholder_marriagemaster.yml` and set the `enabled` option to `false`.

2. update your UltimateChat to the latest dev build: http://host.areaz12server.net.br:8080/job/UltimateChat/229/artifact/UltimateChat-Sponge-8/target/UltimateChat-1.8.9-b229-Universal.jar

**Comment by MithrandirCraft** [comment]
The plugin loads without errors now, but according to reports (will confirm this myself), you can set a home, but you can't teleport to it...

I also see these strange errors on console:
https://gist.github.com/MithrandirCraft/0b763f294d4690b1729de6c3d81dda8e

**Comment by GeorgH93** [comment]
Please update all your servers (including the BungeeCord) to Marriage Master v2.

**Comment by MithrandirCraft** [comment]
Well, they're all using 2.X+
Allthough Survival is using 2.0.5-RC3-Release which you gave me personally. May be related to the issue.

I'll set them all to the version you gave me for now.

**Comment by GeorgH93** [comment]
Please check your BungeeCord again, the communication format for BungeeCord has changed with v2.
And `home|<username>` is the old communication format.

Also I have already released v2.0.6 with some more bugfixes ;)

**Comment by comonier** [comment]
> > all my plugins have problems with this latest or oldest builds, some error in bukkit communications.
> > `[02:25:42] [Server thread/INFO]: [FeatherBoard] An error occurred while initi ....
> 
> 1. open the file `plugins/FeatherBoard/placeholders/placeholder_marriagemaster.yml` and set the `enabled` option to `false`.
> 2. update your UltimateChat to the latest dev build: http://host.areaz12server.net.br:8080/job/UltimateChat/229/artifact/UltimateChat-Sponge-8/target/UltimateChat-1.8.9-b229-Universal.jar

after that the heart of marry tag on uchat disapear

**Comment by comonier** [comment]
![image](https://user-images.githubusercontent.com/19571541/61584375-d277a080-ab1c-11e9-95e5-a17f283c740d.png)

**Comment by GeorgH93** [comment]
> 
> 
> > > all my plugins have problems with this latest or oldest builds, some error in bukkit communications.
> > > `[02:25:42] [Server thread/INFO]: [FeatherBoard] An error occurred while initi ....
> > 
> > 
> > 
> > 1. open the file `plugins/FeatherBoard/placeholders/placeholder_marriagemaster.yml` and set the `enabled` option to `false`.
> > 2. update your UltimateChat to the latest dev build: http://host.areaz12server.net.br:8080/job/UltimateChat/229/artifact/UltimateChat-Sponge-8/target/UltimateChat-1.8.9-b229-Universal.jar
> 
> after that the heart of marry tag on uchat disapear
Enable this option:
https://github.com/GeorgH93/MarriageMaster/blob/master/resources/config.yml#L89

**Comment by comonier** [comment]
ty - its working now

**Comment by MithrandirCraft** [comment]
Some users that write marry home now get a message telling them they are not married, however they do show up as married on the list...

**Comment by GeorgH93** [comment]
Please tell me:
1. Are the players that experience the problem only newly married (since the last restart of the BungeeCord) players?
2. Can they perform other global actions (if enabled) like chat or tp?

**Comment by MithrandirCraft** [comment]
1. They're old married players, I tried it with some characters I recently married myself, and everything works fine.

2. Yes. All other functions of marriage master work. Maybe something's wrong on my database.

**Comment by GeorgH93** [comment]
Please send me your plugin config from the BungeeCord and the used BungeeCord version.

**Comment by MithrandirCraft** [comment]
It's a default generated config. When I updated, I tried to copy a new one which I'd already configured, apparently it didn't like it, and declared it as _old
The one currently is a newly generated one. Does it need to be configured like the rest? It's a bit strange that the bungee plugin would generate the same configuration as in the rest of servers.

**Comment by GeorgH93** [comment]
The BungeeCord config is mostly the same as the Bukkit config (some keys removed and very view keys added and the versions are different Bungee is on 100 Bukkit on 94).
The options that are available on Bukkit and BungeeCord should be set to the same values, especially the Database and Marriage settings.

Your Bukkit config (the one you posted previous) does not use UUIDs and the default config does, so that could be the cause of the problem (the UUIDs of your players in the database not matching their real UUID).

**Comment by MithrandirCraft** [comment]
I'll configure the bungee one by hand, since it seems like it may be slightly diferent.

**Comment by MithrandirCraft** [comment]
This was generated on bungee by the way... kinda strange that priests are twice:
![imagen](https://user-images.githubusercontent.com/6623704/61997497-89869580-b0a2-11e9-93f9-766155ca8638.png)

**Comment by GeorgH93** [comment]
Thanks for the info, somehow there was the wrong key for the priest table in the config template. I will fix this with the next update.
The `Priests` key should be the correct one.
