### ISSUE TITLE
Error on Spigot 1.11.2 !

### ISSUE THREAD

**Issue by TheIntelloBox** [GeorgH93/MarriageMaster#8]
[23:06:55] [Server thread/WARN]: [MarriageMaster] Unhandled exception executing command 'marry' in plugin MarriageMaster v2.0-SNAPSHOT-T20170213165034
[23:06:55] [Server thread/WARN]: java.lang.ArrayIndexOutOfBoundsException: 0
[23:06:55] [Server thread/WARN]: 	at at.pcgamingfreaks.MarriageMaster.Bukkit.Commands.ChatCommand.getHelp(ChatCommand.java:190)
[23:06:55] [Server thread/WARN]: 	at at.pcgamingfreaks.MarriageMaster.Bukkit.Commands.ChatCommand.getHelp(ChatCommand.java:45)
[23:06:55] [Server thread/WARN]: 	at at.pcgamingfreaks.MarriageMaster.API.MarryCommand.doGetHelp(MarryCommand.java:169)
[23:06:55] [Server thread/WARN]: 	at at.pcgamingfreaks.MarriageMaster.Bukkit.Commands.HelpCommand.execute(HelpCommand.java:52)
[23:06:55] [Server thread/WARN]: 	at at.pcgamingfreaks.MarriageMaster.Bukkit.Commands.HelpCommand.execute(HelpCommand.java:31)
[23:06:55] [Server thread/WARN]: 	at at.pcgamingfreaks.MarriageMaster.Bukkit.API.MarryCommand.doExecute(MarryCommand.java:135)
[23:06:55] [Server thread/WARN]: 	at at.pcgamingfreaks.MarriageMaster.Bukkit.Commands.CommandManagerImplementation.onCommand(CommandManagerImplementation.java:177)
[23:06:55] [Server thread/WARN]: 	at at.pcgamingfreaks.Bukkit.RegisterablePluginCommand.execute(RegisterablePluginCommand.java:132)
[23:06:55] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[23:06:55] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchCommand(CraftServer.java:649)
[23:06:55] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.PlayerConnection.handleCommand(PlayerConnection.java:1344)
[23:06:55] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1179)
[23:06:55] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
[23:06:55] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:1)
[23:06:55] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13)
[23:06:55] [Server thread/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[23:06:55] [Server thread/WARN]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[23:06:55] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46)
[23:06:55] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:739)
[23:06:55] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399)
[23:06:55] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675)
[23:06:55] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574)
[23:06:55] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:745)

**Comment by GeorgH93** [comment]
Should be fixed now: https://ci.pcgamingfreaks.at/job/MarriageMaster%20V2/12/artifact/target/MarriageMaster-2.0-SNAPSHOT.jar
